#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Shared Intentionality | Constant
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/constant--shared_intentionality.org
:Created:   2017-10-29T20:37@Prek Leap (11.642600N-104.919210W)
:ID:        665fe108-b6fe-4697-bf08-4277a95a8e13
:VER:       562556339.869523453
:GEO:       48P-491193-1287029-15
:BXID:      proj:AQG5-2076
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

#+begin_quote
Another way of describing this transition from the cognitive
abilities of animals like dogs to those like the ones we
have is to say that most animals understand the world just
in a causal manner, while we also comprehend the
informational connections between things. Moreover, we are
capable of creating information connections between things.

You can do a simple experiment with a dog: try to point to
something in order to tell him to go there. The dog will
just look at your finger. If you move your finger it will
follow its motion. It is just incapable of understanding the
idea that you're pointing at something. If you pretend to
throw something to a certain location the dog might go
looking for what it thinks you have thrown, but it will not
understand you when you're just throwing information.

We find the idea of pointing at something so natural that it
is difficult to understand how complex this process really
is. In fact in the wild not even chimpanzees use pointing -
although when you point to things they can do better than
just to look at your finger. Chimpanzees use pointing in the
wild when they want to indicate to some other chimp that
they wish to be scratched in some hard to reach point, but
they don't point to other objects or animals.

The ability of understanding informational relations depends
on the ability of attributing goals to others because any
information serves a certain purpose. If it wouldn't it
wouldn't be information but just a causal relation. However,
informational relations exist independent of whether there
exists somebody capable of understanding informational
relations. All the processes that make life possible are
informational - the DNA stores certain information about how
the life form must look like and behave, and this
information is decoded by the chemical processes in the
cell. Moreover, the blood carries not only the nutrients or
the hemoglobin with oxygen, but also information in the form
of hormones. And then of course there is the more modern
informational highway - the nervous system. (Read more on
information.)

What I want to point out is that there are animals that have
goals, but that are incapable of attributing goals either to
others or to themselves. A bird for instance has a set of
quite complex goals: it gathers leaves and sprigs for the
purpose of building a nest, and it builds a nest for the
purpose of keeping its chicks safe. But it isn't capable of
understanding goals. It understands a predator for instance
because the predator has certain properties and the bird
reacts in such and such a way to a thing that has those
"predator" properties. A dog can have the purpose of finding
you when you're playing hide-and-seek, but, amazingly, it
cannot understand that you have the goal of hiding from it
(see article).

---

We reach our cognitive limits about here: We can be aware
that somebody A is working together with B using some tool C
for achieving the common goal D. This relation between four
items is called "shared intentionality" by Michael
Tomasello. As you can notice, we don't even have a word in
usual language for this type of relation. Nonetheless, it is
quite important and it has plenty of consequences.
(Tomasello and his colleagues describe some of them in this
paper.)

This type of behavior can be observed even among
monkeys. For example I have seen a particularly spectacular
clip with a bunch of baboons throwing stones at a lion and
driving it away. But a baboon cannot even understand the
concept of goal, even less that of shared
intentionality. Nonetheless, sometimes they are doing it.

When things get more complicated and we need to follow many
items at once we are grouping them together based on some of
their properties. For example, it would be literally
impossible for the human brain to follow a football match if
the teams wouldn't wear uniforms - thus making it easier for
us to think the whole situation as "team A against team
B". Researchers have discovered that we have serious
difficulties in dealing with more than three groups of
objects at once. (Read article.)

-- [[http://news.softpedia.com/news/The-Limits-of-Human-Cognition-37388.shtml][The Limits of Human Cognition]]
#+end_quote


#+begin_quote
"We found that humans are unable to store information from
more than three sets at once," Halberda said. "This places
an important constraint on how humans think about and
interact with sets in the world."

-- [[http://news.softpedia.com/news/Why-Are-Uniforms-Uniform-27392.shtml][Why Are Uniforms Uniform?]]
#+end_quote

#+begin_quote
 For those who find it tough to juggle more than a couple
 things at once, don't despair. The brain is set up to
 manage two tasks, but not more, a new study suggests.

That's because, when faced with two tasks, a part of the
brain known as the medial prefrontal cortex (MFC) divides so
that half of the region focuses on one task and the other
half on the other task. This division of labor allows a
person to keep track of two tasks pretty readily, but if you
throw in a third, things get a bit muddled.

"What really the results show is that we can readily divide
tasking. We can cook, and at the same time talk on the
phone, and switch back and forth between these two
activities," said study researcher Etienne Koechlin of the
Université Pierre et Marie Curie in Paris, France. "However,
we cannot multitask with more than two tasks."

-- [[https://www.livescience.com/10992-3.html][Why We Can't Do 3 Things at Once]]
#+end_quote


And of course there is a price to be paid for context switching...


#+begin_src bibtex
@article{tomasello:2007shared,
  title={Shared intentionality},
  author={Tomasello, Michael and Carpenter, Malinda},
  journal={Developmental science},
  volume={10},
  number={1},
  pages={121--125},
  year={2007},
  publisher={Wiley Online Library}
}

@article{charron2010divided,
  title={Divided representation of concurrent goals in the human frontal lobes},
  author={Charron, Sylvain and Koechlin, Etienne},
  journal={Science},
  volume={328},
  number={5976},
  pages={360--363},
  year={2010},
  publisher={American Association for the Advancement of Science}
}

#+end_src
