#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Yellow Brick Road: A Manifesto
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-manifesto.org
:Created:   2017-08-24T18:30@Prek Leap (11.642600N-104.919210W)
:ID:        659c2b13-181c-4bab-8f7b-c23033fe6d95
:VER:       556846285.464337387
:GEO:       48P-491193-1287029-15
:BXID:      proj:CCH5-8007
:Class:     deply
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* A Manifesto for a Distributed Civilization


#+begin_quote
The Earth is the cradle of the mind, but we cannot live
forever in a cradle. 

-- Konstantin Tsiolkovsky (1857-1935)
#+end_quote


#+begin_quote
You can't cross the sea merely by standing and staring at 
the water.

-- Rabindranath Tagore (1861-1941)
#+end_quote


#+begin_quote
You begin saving the world by saving one man at a time; all
else is grandiose romanticism or politics.

-- Charles Bukowski (1920-1994)
#+end_quote

#+begin_quote
Pass it on .... That's the game I want you to learn to play.
Pass it on.

-- Alan Bennett, /The History Boys/
#+end_quote

* I.   The Yellow Brick Road

Is there anybody out there?  The question hangs in the air,
everyone holding their breath, straining to hear in the
uncomfortable silence.  We are terrified of being alone,
alone in the dark, in the crowd, to be the first to speak
out, and to wake in the middle of the night with no one
beside us.  But we are just as scared of who might be out
there in the darkness beyond the warm flickering safety of
the fire; a lion, a monster, a ghost of those and those
things we don't care to remember or re-live.  Part of the
problem is that as a species we evolved to be in the middle
of the african savannah ecosystem.  We weren't at the
bottom, but we certainly weren't at the top.  Lions and
tigers and bears, indeed...

Our ascension to the top of the food chain was recent and so
rapid that the slow mills of evolution didn't have time to
grind out the psychological perks that come with being an
apex predator.  We don't have the casual confidence or raw
muscle of the lion, the deft, deadly resolve of the tiger or
the plodding heavy certainty of the bear.  In the end we are
still fearful apes who have just come down from the branches
long enough to make a mad dash for the next clump of trees
where there are some tasty looking figs.  So even today we
still whisper, often secretly to ourselves, "is there
anybody out there," uncertain if we really want to know.
But there is no answer, not yet.

We live in a cosmos made up of hundreds of billions of
galaxies flying apart from the explosion that gave birth to
our universe.  Each galaxy is made up of hundreds of
billions of fireballs burning holes in the fabric of
spacetime as they orbit, hurtling around each other.  From
time to time one may collapse into a darkness so absolute
that not even information can escape.  Other times some may
explode and for a brief moment outshine all of the other
fireballs in the galaxy, to become vast gas clouds of
astonishing beauty that in turn become the stellar nurseries
where new stars are born.

As gravity clumped, collided and collapsed the gas and dust
into itself, a star was born some 13.7 billion years ago in
such a nursery, in an uninteresting part of a spiral galaxy
we now call the Milky Way.  Orbiting this star are nine
planets, and billions of planetoids made up of rock, iron
and ice, including a small rocky world orbiting close enough
to the star for there to be water in a liquid state.

The more we learn about the universe and our place in it,
the more it's clear that there is nothing special or unique
about us.  We are now discovering, almost every day, the
rocky worlds and gas giants that are orbiting the stars in
our stellar neighborhood. In the coming decades we will have
the ability to learn the composition of the atmospheres of
these worlds.  There is no reason to think that we won't
find other worlds, close enough to their stars to be water
worlds like ours.

But if there is nothing special about us, then it's
reasonable to expect that life will have evolved on other
planets and might even be relatively common.  And, that on
some planets where there is life, that a species evolves 
to build a technological civilization like ours.  

So where is everybody?  This question is known as the Fermi
Paradox.  There is a long list of reasons we haven't yet
found evidence of other technological civilizations, but
there is one reason that haunts the dreams of many
scientists.  What if the reason that we haven't found anyone
out there is that technological civilizations are are by
their very nature so unstable that they destroy themselves
shortly after the start of their own scientific revolution.

Is this our fate as well?  Are technological species little
more than mayflies that have a brief frantic existence
before falling dead in the dark hours before dawn?  It's
called the Great Filter, the existential moment of truth
that a technological race must face after they have unlocked
nuclear forces that power the stellar infernos.  Or, perhaps
what destroys them is learning how to reshape the structure
of life itself as if it were nothing more than a child's set
of lego bricks.  Or, that in their ignorance and immaturity,
they leverage their new found technological prowess to do
nothing but overrun their planet with their numbers, exhaust
all easily exploited mineral and energy wealth and exceed
their planet's carrying capacity and then collapse and not
have the resources to re-build an industrial civilization.

If this sounds familiar it should be.  If we fall now, there
is no rebuilding. The surviors will eek out an existence as
best they can until an asteroid or super volcano, or ice age
finally puts an end to the great human experiment.

Our ancestors understood that there were forces in the
universe which even the gods could not escape, to which they
they gave names like Fate. Fate could not be petitioned, or
sacrificed to, or even hear us if we did.  The Gods might
intervene in some small ways on our behalf, if they could be
bothered.  But ultimately these things were beyond even the
vast powers of the immortals.

It was thought that these forces determined what and how
things happened, but it turned out that fate was nothing
more or less than the physical laws of the universe which
are governed by the complexity of everything interacting
with each other.

You can predict the outcome of simple systems.  But once a
system crosses a threshold of complexity, all there is, is
statistics.  It's a bit like the game of Go.  In Go, binary,
black and white stones are placed on a grid cut into a block
of wood.  We thought that Fate and the Gods added, removed
and moved stones on the board in a dance that we could not
understand, control or predict.  Instead, stones are dropped
onto the board at random, white and black with an equal
chance of any stone landing on any square. What you get is a
Poisson Distribution where you can predict how many squares
on the grid will have how many stones, but not which squares
will have which number of stones.

There is no prayer that can change the certainty of our
uncertainty.  As individuals we must each learn to make
peace with the unknown.  Our consolation is that over time
scales that are beyond the living memory of any individual,
we contribute to collectively beat fate, pass the test and
make it through the Great Filter, but only if enough of us
as individuals today, and tomorrow, decide to do so.

This is the great task we must choose or perish trying.
This is where we must begin, with a single step, at the
center of a widening path spiraling out into a vast kingdom
that we still know little about.  Each tenuous step forward
will often require us to retrace our steps back.  But there
is nothing for it but to push on down the yellow brick road
to learn something that, or meet someone, who can help.

* II   Filters

start with life arising after the earth cools -- it could
have arisen here, or elsewhere and piggybacked on a comet or
meteriod -- it's possible it might even be from another
star, riding on a piece of rock ejected from another planet
on another star at some distant time in the past when our
star brushed up against our neightbor's Oort cloud and
exchanged debris -- caught in our Oort Cloud for millennia
before some random event pulled it in towards the sun but
impacted earth first.  we will only know if we ever visit
the stars and find life there that is us... In any event,
somehow, some xxx years ago life began.

filters for life on earth have come in the form of five
great events that resulted in catastrophic climate change
where 75-96% of species on the planet were wiped out

 - End Ordovician, 444 mya, 86% of species lost 
 - Late Devonian, 375 mya, 75% of species lost
 - End Permian, 251 mya, 96% of species lost
 - End Triassic, 200 mya, 80% of species lost
 - End Cretaceous, 66 mya, 76% of all species lost

life is tenacious and antifragile, once it takes hold, it's
astonishing how much punishment it can take and eventually
rebound, stronger and more complex than ever.

the extinction events have acted like the black plague that
wiped out xxx% of the world's population, or the great fire
of london -- it cleaned things out and reset the clock
setting the stage for an evolutionary explosion of new life
racing to fill in all of the ecological niches that had been
left vacant. without the past four extinction events life on
earth may well only be marginally different from how it was
in the Ordovician.  Life has a tendency to reach
equilibriums that can last a very very long time.

the patterns are very clear, and they scale -- climate
change, carrying capacity of an ecosystem, carrying capacity
of a biosphere -- impact the climate and you change the
carrying capacity -- when this happens to an ecosystem in a
biome species go extinct.  when this happens to the
biosphere, you get mass extinction events.

mankind has moved from the small stage of impacting and
being impacted by specific biomes, to being a major player
effecting the entire biosphere.  and we're now doing this in
timescales that can be measured in 2-3 generations.  if that
doesn't blow your mind you weren't paying attention.  if it
did blow your mind and you aren't terrified then there is
something wrong with you.  and if we as a species aren't
terrified by this enough to change our behavior then we are
lost.

* III  Savannah

The road for us really started in the African savannah, the
biome where we evolved and became what we are along side a
number of other cousins of great apes including our closest
cousin the Chimpanzee.


A savannah is a biome between worlds, stalled in the process
of evolving from a grassland to a forest.  Savannah biomes
are enormously productive and varied, with the advantages of
both grasslands and forests while making both stable and in
harmony with each other.  Where grasslands are the domain of
annuals which die out every year, and forests are dominated
by perrenials which often live decades or even centuries
under the right conditions, a savannah is a balance between
the two, and so support a wider variety of both flora and
fauna in an ecosystem which is resiliant to a wider variety
of climatic and other types of change than.

Fauna make a savannah what it is, with a combination of mega
fauna which both graze grasses and keep the ground clear
beneath trees and by knocking down or tearing up most small
trees that would otherwise eventually grow to replace the
grasses.

Some 6 million years ago, we shared an ancestor who had two
chilren, one which would evolve to become the Chimpanzee and
the other would become the genera /Homo/ which means Man.

/Homo Neanderthalensis/ (man from the Neander Valley) who
was larger and stronger than us, dominated north western
Eurasia and was adapted to the cold of the Ice Age.  /Homo
Erectus/ (upright man), was adapted to the warmer African
climate who lived for almost 2 million years.

On the island of Java in what is today called Indonesia
there was /Homo Soloensis/, (Man from the Solo Valley) who
was well adapted to life in the tropics, and the species
recently discovered in Flores called /Homo Floresiensis/
which reached a maximum of a bit more than a one meter in
height.  In 2010 the finger bone of a previously unknown
species, /Homo Denisova/ was discovered in the Denisova Cave
in Siberia.  We may never know how many other lost species
of ours there are to be found.

Meanwhile, in the African savannah, the cradle of humanity,
new species evolve including /Homo Rudolfensis/ (man from
Lake Rudolf), /Homo Ergaster/ (working Man), and our
species, who was modestly named by Linnaeus in 1758, /Homo
Sapiens/ (wise Man)

A hundred thousand years ago there were at least six
different human species living at the the same time, spread
across the planet.

It's still uncertain why any one species vanished, though
there are many theories that all posit that we were
responsible for the demise of some species when sapiens
moved into the territories of other species.

The Toba super erupution that took place around 75,000 years
in what is now Indonesia coincided with the extinction of
most species of Homo and almost took us with it.  From
genetic evidence, the human population was reduced to only a
few thousand individuals who had all come out of africa.
For a long time it was thought that the eruption was
responsible for our near extinction, but there is a growing
body of evidence that man was able to cope with the
erruption quite well and that little volcanic ash reached
east Africa which quickly recovered.

----

Mankind is a broader concept than a catalog of species of
the Homo genera.  The Savannah is an ecosystem of
interdependent species of which, for most of sapien's
history was in the middle of the food chain.

Man domesticated a number of animals who would not survive
without us, they are part of us, and we depend on them for
the survival of our species as much as they on us.


We must learn to reclaim the savannah as part of ourselves,
it is not only where we are from, but what we are.  And when
we leave the planet to spread our species and civilization
across the solar system, and eventually to the stars, we
will bring the savannah with us.

* IV   Cognition

- extend & externalize
   - mind  : brain, speech, writing (havelock), computer
   - muscle: hand, tool, machine, robot
 - transactive man
 - cooperation & war
 - polis -- the rise of annuals and decline of perennials
 - pace layers

 - cognitive revolution
   - we had to give up our intestines which provided more
     energy for the brain but limited our diet -- so without
     cooking we survive poorly
   - we gave up our hearing to dogs
   - childbirth became quite dangerous
   - children born prematurely -- need long period of care
     but means that children's development can be molded
   - we have more nerve endings in our hands

  - we are the planet's apex predator and keystone species,
    capable of destroying everything, we are close to being
    able to consciously control of our dna not only of our
    selves but all life on the planet, we are also close to
    conquering death, so the only thing left that is certain
    is taxes.

    the problem is that we moved up the food chain because
    of cognitive development, it happened too fast for the
    surrounding ecosystems to adapt to us as the new apex
    predator which would have put checks and balances on
    human growth.  second, man may have become smarter, but
    she is still saddled with all of the baggage of an
    animal in the middle of the food chain -- we don't have
    the self-confidence of an apex predator.  It's like
    giving a cow an uzi, vegitarian megafauna like cows know
    that they are on the menu of a wide variety of
    predators, so they are nervous and easily spooked.  Give
    them a WMD and they would hit the button at the first
    unexpected sound of a snapped twig in the grass.
    human's are that much better.

  - stories make cooperation between large groups possible
    - havelock and homer as oral cultural encyclopedia

  - between 70-30kya sapiens developed speech -- if near
    human extinction happened 75kya that corresponds to
    development of human speech only a few thousand years
    before?



  - stories -- gossip makes larger groups possible


* V    Fragility

 - pale blue dot
 - the skin of an apple
 - all the air, all the water
 - that's all there is, a friable oasis that in cosmic
   scales is as ephemeral as a soap bubble.  like the tiny
   world that Horton the elephant discovers inhabiting a
   mote of dust sitting on a cloverleaf.




 - fragility of our biosphere
   - asteroid and comet strikes
   - solar storms
   - super volcanos
   - hothouse coldhouse

 - fragility of our species

 - fragility of our civilization

 - the idea of progress is a recent infection carried by the
   scientific revolution -- it drives us, but it does not
   direct us in the right direction.  the grasping always
   for more has inspired us as a species, but it has also
   blinded us, made us reckless and squander resources as if
   they were infinite, as if our planet didn't have a
   carrying capacity.  But time and time again, human
   civilizations have run up against the carrying capacity
   of their environment and it always ends the same,
   collapse.  But there was always another civilization
   which could pick up the pieces and rebuild.  We've now
   taken this to it's logical conclusion, there is no where
   left on the planet to go, no greener pastures,
   unexploited resources.  We've finally gone so far that we
   are back where we started.

 - centralized


* VI   Estranged

*NOTE* Estrangement is about specilization and
compartmentalization.

  - communities
  - families    -- replaced by state and market
  - small numbers
  - nutritious variety of diet

  - circadian cycles, light and dark
  - day and night, seasons

  - children are separated from adults most of the time and
    detained in schools so that parents are freed to work in
    factories and offices

  - teens living in separate sub-cultures cut off from
    chilren and adults

  - adults are cut off from their children and their parents
    live by the same regimented schedule every day, and are
    reduced to doing a very narrow range of activities and
    have little free time to be with family, friends, study
    or simple rest and recharge

  - the elderly are left alone without purpose and often
    even without human contact.

  - cut off from the natural environment
  - cut off from the sky and stars
  - our buildings are not fit to live in

  - our towns and cities have been designed to make
    communities impossible

  - many of us no longer know how to process natural plants
    and animals for consumption -- increasingly, we don't
    even know how to cook


* A Social fabric

Cognitive estrangement -- we are brains that learn about the
world second hand through very limited senses that evolved
for specific functions -- we try to piece together what the
world is but it's always a hacked together hodgepodge of
sensory information, memories and conjecture about things
that we don't have direct knowledge of.

We expand what we as individuals can learn about the world,
with intersubjective information from other people through a
cultural encyclopedia of myth, cooperative rules and
language that allows us to both communicate and experience
the world in a similar way with others.  Shared belief
systems take the form of religions, ideologies, folklore,
customs, and ritual.  Religions help us fill in the gaps of
our knowledge of things that we don't know or can not know
with shared stories of divinities who by and large are
little more than cardboard projections of our selves and our
fears and anxieties on the cave wall we believe is the
universe.  This is something that hard core atheists can't
understand.  They see religious belief systems as
objectively false.  But they believe in all sorts of
collective belief systems which are fictions as well. But
it's not about objective or empirical truth, which doesn't
matter much.  A fundementalist Christian who proclaims that
the scriptures are objectively and historically accurate
accounts don't live their lives as if it were true.  If they
really believed such things to be real, they could not
function in a modern technological society.  They use
technology daily that could not have been developed if it
were.  This does not excuse willful ignorance of things like
climate change.  But at the same time it doesn't make them
hipocrites.  Belief is not about being true or false, it's
about shared narratives that make cooperation and
communication possible.

Secular belief systems include things like nationality,
cultural identity, money, the market, and above all the
future.  These belief systems make up the mortar that holds
together the bricks that make up civilization.  They are all
stories, narratives that thread through our individual and
collective world maps that we carry around in our heads that
comprise all we know about the world at any given moment.

We need to learn to see these fictions as stories that we
have made up, while embracing them, not as literal truth but
for the power they wield in getting billions of clever apes
to work together and do astonishing things.  We will always
be storytellers.  It is stories that define us, as no other
species does.  But stories are always a mixture of the
subjective and empirical objective experience.  They form
what I call /fnords/.  A fnord is an assertion which is a
probability cloud of all possiblilities about the statement
both as true or false which don't resolve until they have
been placed in context by observation.

Before the great monotheistic religions, Buddhism,
Christianity and Islam came along, reglions were very local,
they literally sprang from the ground around us in
primordial animistic belief systems grounded in specific
rocks, trees, mountains and rivers.  They weren't terribly
portable if you tried to get people from a different place
with different rocks and trees who had their own ideas of
what they were called.  Monotheism was universal, a stripped
down belief system that could map over any local belief
system and over time mostly replace them.  In other words,
monothesim is a belief system best suited to empires. 

The Romans never tried to replace the local gods of the
lands they conquered, but then they didn't have to.
Polytheism is not a zero sum game.  So long as the conquered
paid lip service to the Roman gods they were free to worship
their local gods however they pleased.  Monotheistic belief
systems could never do that -- you either believed and
became one of /us/, or you were /other/ which needed to be
destroyed.

This inflexibility, surprisingly, was a boon for far flung
empires who demanded that you were all in or nothing.
Harsh, but effective.  But this never entirely worked.
Different groups of people interpreted the single scriptures
differently and began fighting with each other.  It's not
easy to get everyone to believe the same thing, we live in
very different climates, and cultures built to adapt to
those climates.  We experience and see the world differently
depending on our relationship to the natural world.  If you
live in a warm pleasant climate, you tend to see the world
as being benign and even friendly.  If you live in an
extreme climate, the world is a hostile place full of
uncertainty and danger.  We bring those attitudes with us to
every part of our lives.  It's no surprise that the Big
three have never been able to get everyone on the same page
for long.  Sadly, we tend to hate those the most, who are
closest to us.  The wars between catholic and protestants
are some of the most bloody an devastating in history.


 - the mind's illusion
 - myth of progress

 - estranged from ourselves
   - savannah lost

* VII  Natures

The agricultural and industrial revolutions have trashed the
way that all members of Mankind live.  In an blink of an
eye, by evolutionary timescales, all of us, Sapiens and all
the creatures (both flora and fauna) we domesticated and
took along for the ride now live a very uneasy existence
that is out of sync with our natures.

It is not too much to ask that each of our natures be
respected and each us be allowed to live our lives, no
matter how short or long, in a manner that reflects our
natural instincts, strengths and weakneses.

Let's start with plants.  It might sound strange to advocate
that plants be allowed to live according to their natures.
It has nothing to do with attributing human traits to
plants.  It is much more about sound farming and ecological
management practicess.

We now grow a handful of spieces of plants in absolute
artificial monocultures.  We have separated individual
species, almost all of which are annuals, and separated them
from broad ecosystem populated by plants, insects, micro
organisms and animals and forced them to grow on their own.
There is nothing natural about monocultures.  Each plant
places different demands on the soil, both giving and
taking.  In their natural environment they would be
integrated with many other species of plants as well as sub
species of their own species.  Different species compliment
each other.  Some repell destructive insects, others attract
pollinating insects, some return nitrogen to the soil,
others providing forage for mega fauna.  Perennials provide
shade, windbreaks, and deep root systems that keep
groundwater coming to the surface in the form of springs and
streams.  Worms provide and in the tropics, ants aerate the
soil.  Insects pollinate and help break down decaying
biomass.  Micro organisms do for plants what micro organisms
do for humans, some keep us alive, others make us sick but
neither of us can survive without the other.  Birds scatter
the dung of mega fauna and are crucial in seed dispersal.

This system was disrupted in the agricultural revolution,
but small farms still had diversity, peasants still relied
on forests for medicines, and variety in their diets.  And
back breaking labour of humans replaced a wide variety of
chores that are achieved in nature without any effort at all.

It was the second agricultural revolution that was part of
the industrial revolution where things really fell apart.

....

Animals -- go through all the primary domesticated animals,
their natures and how they live now.

....

In many respects man hasn't done much better -- 

  - high stress/fear   -- machiavellian techniques, conformity
  - low stress/comfort -- embrace consensus, egalitarianism

....


   
* VIII Storms

 - goods, people and know how
 - population and the great pin -- as child mortality drops,
   and education increases, birthrate falls  -- this could
   well become the mechanism for man to regulate it's own
   population to compensate for our quick rise to becoming
   an apex predator and keystone species,


 - an end to our clement climate

 - the sound of inevitibility -- "you hear that mister anderson, it's
   the sound of inevitability - Smith"

 - disease
 - black swans, collapse, and world killers 

 - singularity or nightfall 

 - chances of survival (Gott)

* IX   Maps 

 - Map and Territory
 - Legibility 
 - Worldview

 - climate shapes our relationship with the world, and our worldview

   - it could be said that most cultural differences are
     derived from the different way we solve problems to
     adapt to the local climate.  temperature, rainfall,
     proximity to rivers or lakes or oceans, length of days
     and nights are all part and parcel of the mechanics of
     our daily lives.
     
     Contrast the world view's embodied in Homer's Oddessy
     and Iliad and Beowulf. Homer called the Mediterranean
     the wine dark sea.  Echoing Homer, James Joyce called
     the North Sea, the "snot green sea" in /Ulysses/,
     though in Beowulf, the sea is a "whale-road."  Odysseus
     made camp on the beach and partied.  Beowulf headed
     straight to the beer hall, which had no windows and
     only a door and a hole in the roof to let out smoke.
     For Odysseus the world was benign, but controlled by
     bickering and spiteful Gods who could be petitioned for
     help, but who's internecine machinations more often
     brought misfortune for man.  Beowulf's Gods were
     distant and seemingly disinterested in man.  No help or
     intervention was coming, nor was expected, leaving
     Heroes like Beowulf to take matters into their own
     hands to do battle with both monsters and nature
     directly.

* X    Stories

 - stories make cooperation between large groups possible
   -- havelock and homer as oral cultural encyclopedia.

 - ariadne's Thread -- maps, narratives and territories
 - indistinguishable from magic -- mitigating complexity --
   we need mythos to map technology so we can relate to it,
   understand it and use it.
 - language & mythos as interface
 - transcending and returning to human scales

* XI   The Window

 - The Window -- 50 years plus or minus 20

 - the only thing that has saved us after we have fouled our
   own beds and made them uninhabitable is that we move on
   to the next place and reduce pressure on our old homes to
   let them heal, if we haven't destroyed it beyond its
   ability to heal.  we expand or we die.

 - but we are now faced with the fact that we have nearly
   exhausted all of the low hanging fruit -- energy and
   natural resources and our population has exceeded the
   carrying capacity of the biosphere.

 - we need to expand into the solar system -- where there is
   no shortage of natural resources and energy

    - all energy is nuclear, be it fossil fuels, wind or
      solar or our own limmited ability to split or fuse the
      atom

    - it is likely that within a lifetime or two at most,
      the majority of energy that mankind uses will be for
      computation -- even today, Google alone represents 1-2
      percent of energy use in the united states.  solar and
      renewables can likely satisfy all of our other energy
      requirements -- but not computation

* Theses

