#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Manifesto | TOC

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Manifesto | Table of Contents
:PROPERTIES:
:CUSTOM_ID:
:Name:      /home/deerpig/proj/chenla/manifesto/index.org
:Created:   2017-10-06T18:08@Prek Leap (11.642600N-104.919210W)
:ID:        730bbfc9-e0cb-4c6f-97e0-4dbdef81b4d9
:VER:       560560166.539684901
:GEO:       48P-491193-1287029-15
:BXID:      proj:TWT0-8431
:Class:     primer
:Entity:    toc
:Status:    wip 
:Licence:   MIT/CC BY-SA 4.0
:END:

** The Yellow Brick Road: A Manifesto

** Epigraph

#+begin_quote
I have to learn the simplest things 
last.  Which made for difficulties.
Even at sea I was slow, to get the hand out, or to cross
a wet deck.
            The sea was not, finally, my trade
But even my trade, at it, I stood estranged
from that which is most familiar.  Was delayed,
and not content with the man's argument
that such a postponement
is now the nature of 
obedience.
              that we are all late
              in a slow time,
              that we grow up many
              And the single
              is not easily
              known

— Maximus, to himself
  Charles Olson  
#+end_quote


** Preface

#+begin_quote
The crisis consists of the fact that the old is dying
and the new cannot be born,  In this interregnum, a great
variety of morbid symptoms appear.

— Antonio Gramsci, /Prison Notebooks/
  quoted by Edward Dorn cite:dorn:2007ed-dorn-live
#+end_quote


#+begin_quote
“Men and nations behave wisely when they have exhausted all
other resources.”

— Abba Eban, 1967
  https://quoteinvestigator.com/2012/11/11/exhaust-alternatives/
#+end_quote

After nearly 20 years labor, I return from the wilderness
with a question.  Can Man have it all?  10 billion plus
souls living at a high standard of living in an
technogically advanced that is within the bounds of a
sustainable carrying capacity and healthy biosphere?

as things stand today, no

but my answer is, conditionally yes, and I'm reasonably sure
how, but it won't be what you think and require very hard
changes that again are not the changes you'll be
expecting...

above all it will take the one thing we are wont to give, time.

the cost to get from here to there will be staggering --
partly because we're human, and humans have never managed to
get anything right the first time before.  There is no
reason to believe that this time will be any different.

it will also be uneven, not because it has to be, but
because it will be -- most of us, nor most of our children
will live to see the promised land though some of them might
live to glimpse it.  And even when the promised land is
finally reached it will take generations more before all of
the slow-layers can catch up.  

Utopias are dreams, and as such are worth aspiring to even
though we know they can never come to pass.  But hope is a
wholly different genus.  Dreams are helpful, but hope is
essential.  Hope, the last thing to escape Pandora's box is
the flame that can not be given, it must be sparked,
nurtured, protected, and kept alive despite all odds, lest
it be blown out from the slightest puff of air.  It is hope
that is what is needed more than anything, for us to carry
on and survive -- the fragile seemingly madman's hope that
we can build a better world.

that is the good news, and it's better news than we have at
the moment.  Belief in lies and impossibilities is nothing
more than escapism, a coping mechanism we can no longer
afford.  the future can be bright, but not for us.  and we
need to accept and come to terms with what can be done, and
what we have to atone for and just get on with it.

that is what this work is all about, how we can go back to
first principles and get on with it.

------- let's try again


#+begin_quote
The application of human intelligence to all
phenomena. . . [is] /the/ ordering agent.

— Human Universe
#+end_quote

Ideal polis in which authority is invested in each citizen
individually

#+begin_comment
The problem with what I wrote below is it's too strong.
Scaring people isn't going to help -- we need to keep this
more neutral or move the manifesto out of w&w.  perhaps we
don't need the manifesto at all... the books aren't going to
convert people -- that will be Contact's job.

Fear doesn't work -- we need a meme of a new social contract
that will attract people to join the Middle.

  The Culture
    - Middle : the ai&network that replaces middlemen
    - Contact
    - Special Circumstances

#+end_comment

The problem is that we have forgotten how to live in the
territory, all we now do is live in a matryoshika of nested
maps!  The map used to let us navigate the world, but we
have let so many others make maps for us that we no longer
see what they map.

Aristotle may have kicked this off with his logic and
interminable classifications, but it's all the others who
came after from the Christians and Muslims insisting that
all maps be built on top of their creaky Bronze Age
overlays, and the endless irritations from Dante and Milton
to Marx and the shallow emptiness of Rand. We handed over
the very foundations of cultural muthos and the bones of
language itself to shills like Disney, washing the world of
its warts, sharp edges and brutality, lulling the young into
believing in happy endings and safety and fairness.  The
stories Disney appropriated held none of this.  He went
further not content with the stories of the old country
populated by a complex ecosystem of indifferent, dangerous
and sometimes sinister spirits and creatures, to literally
buy out the strange sometimes edgy stories of Carrol, Milne
and Barrie.  When you visit any of the Disney.* properties
you will see incarnations of Pooh, and Tinkerbell and the
Cheshire Cat, in a cornucopia of commercial incarnations
purchase you can take home, but none of the original books.

We worry that people believe that Facebook is the internet
but don't even raise an eyebrow to the likes of Disney's
annexation of our cultural mythological storehouse.

This was all inevitable once we had contrived the written
word, and then the printed word and now the ghosts of
printed words flickering on brightly lit displays like
shadows in Plato's cave wall that now are seldom more than
captions for captured images and sounds, masquerading as
snapshots of the world.  A whole generation now experiences
the world through the augmented filter of a viewfinder.

We must clear out all the crud and make our maps of the
world through direct experience.  We can learn from other's
maps, but we cannot


--------

I am coming to the conclusion that wizards and prophets are
not so much opposed to each other as one might think.

The wizard has traditionally represented centralized
technological solutions because initial solutions usually
only work at large scales.  Centralized systems are used for
processes that are no economical to do at smaller scales.
But as more is learned, centralized systems become smaller
and smaller until they become more efficient at the edge of
networks which are distributed.  Amazon, Google and Facebook
would not exist if the things they do could be done at
smaller scales.

One problem is that once you get these very large centralized
systems, they become an intelligence in their own right, and
that comes with a survival instinct.  They will fight like
hell to survive and grow, even if they are no longer needed.

That's what happened with Ma Bell.  Microsoft hit that wall
and narrowly avoided being broken up, but instead were
relegated to corporate middleware, and employee interfaces.

IBM lost their position as king of the hill to see their
market fracture into minicomputer companies like DEC and
Wang and later Sun and SGI.

The PC revolution broke things up further giving birth to
countless PC companies, some of which became monsters like
Dell.  

This happened because of Apple, which had the vision, but
Job's was too much of a control freak and perfectionist --
who created beautiful but expensive and inflexible products.
Jobs sold people on the vision of personal computering.  It
was Gates who didn't care about beauty or even quality and
was focused on delivering a minimal viable product and
selling as many of them as possible.  Gates' vision was that
of any 20th century industrialist.  He rode on Job's coat
tails.  And predictibly Jobs imploded -- and when he
returned he abandoned his original vision of general purpose
compters for everyone and found that he could create
consumer electronics where his obsession with beauty and
absolute control worked all too well.  In that sense I would
never call him a prophet and he was never a wizard.  He was
a flawed visionary who was tied to all sorts of nonsense
that contributed to his early death.  The idiot put all of
his faith in crackpot "alternative" medicine and food
ideologies like veganism, that are impossible to strictly
adhere to and not die.

It's also interesting to contrast Job's and Gate's in other
ways.  Jobs was never a philanthropist, he believed that his
vision was his gift to the world.  Gates has followed the
tried and true path of all robber-barons, believing that
through his largess by funding great humanitarian works will
compensate for the wreckage that his ambition and greed left
in its wake.  That's not a bad thing.  Look at the good that
has been done by foundations set up by Ford, Carnegie and
Rockafella, to name a few.

   My company was on the short end of that ambition in the
   90's. We were an early Internet company based in Hong
   Kong. The Internet, from day one, ran on Unix, we didn't
   use MS products.  Our system used sparc stations, SGI
   servers and later a couple of boxes running early
   versions of Slackware.  We /couldn't/ use MS products --
   they couldn't do the job.  We didn't compete in any MS
   markets.  Sadly, one of our staff (our one expat hire)
   was an MS fan and convinced us to help MS with the Hong
   Kong launch of Windows '95.  We spent about US$5K to set
   up a temporary leased line (it was very expensive back
   then) to our data center and provide an Internet
   connection for the launch.  We only asked that our
   company be given credit for the connectivity.  Of course
   that didn't happen.  Then to add insult to injury they
   called up a few weeks later and offered us free licences
   and then later free hardware to switch to NT.  It was
   physically impossible for us to do so even if we wanted
   to.  NT didn't have the network support for TCP/IP needed
   for Internet servies.  We politely said no thanks. So
   they went after our engineers and tried to hire them
   away.  Our engineers said no thanks because they didn't
   like working with the MS Windows/NT operating
   system. Finally MS offered to pay them to not work for us
   and upped the offer.  When I found out, I told them to
   take the money and start their own company with my
   blessing, which they did. It would have been stupid to
   pass up that kind of money.

   After the dotcom crash we moved to Japan and into
   computer animation.  MS was then out to crush SGI and
   bought out Softimage and ported it to NT which was wasn't
   very good.  We had a couple hundred thousand invested in
   SGI hardware, and had licences for Softimage and Power
   Animator (now called Maya).  We tried to upgrade our
   licence for Softimage for our hardware and MS said that
   we couldn't (the upgrade was available but only big shops
   were allowed to get the upgrade) they were trying to
   strong arm small shops like us into moving over to NT.
   They told us they would give us free licences for the NT
   port.  I said no thank you, and they called back next
   week and offered to give us free hardware to run it on. I
   said no thanks. SGI had far far better hardware but it
   was very expensive.  They began loosing marketshare and
   eventually made the mistake of selling workstations that
   ran NT.  It was all downhill from there.  As soon as SGI
   had been crushed, MS sold Softimage to AutoDesk --
   mission accomplished.

   Did any of this substantially hurt us?  In the larger
   scheme of things, no.  But then we were always a very
   small fish. The bigger fish in the pond got hit far
   harder than we were.

   Fast forward close to thirty years and I am now working
   in R&D and the non-profit sector and last month we
   indirectly ran into Gates again and he hasn't changed at
   all.  He's running his foundation the same way he ran MS.
   There are some pretty hefty strings that come with his
   grant money, all of which ensure he will see a large
   financial return on all Grants. If they approach us in
   the future, we will again, politely say no and hope for
   the best.

   This is the same playbook that Facebook is running now
   without the overt personal mafia-style tactics.  They
   don't have to, everything is online now.  You don't have to
   screw people in person any more.  The game never changes,
   just the name of the players.


But the power had moved to the edge of the network and
that's where the Wizards went as well.

When the Internet came along the Wizards saw how they could
not only network PCs together over a network, but wire them
together into cluster -- commodity share-nothing clusters
replaced mainframes and minis alike.  The PC became the
atomic unit of computing machines.

The prophets are not makers, they might have the vision but
they don't have the skills or the resources to make that
vision happen.  The wizards have the skills but not the
resources, so they find backers -- as Neal Stephenson said,
the hacker and the backer is the oldest relationship in the
world.  In some cases that's enough.  The hacker creates, or
discovers, but seldom has a vision -- that's the job of the
prophet.  The wizard-prophet is a rare creature but has has
largely filled that role to date.  The wizards work for the
wizard-prophets and the backers stand in line to give them
resources and wait for the money to roll in.

Prophets have had a hard time of it, because they are too
far ahead of the curve, wizards create things that work,
prophets envision things that are right.

I believe that those two worlds are coming together.
Prophets might be right, but their solutions are too
expensive and can't be made to work.  But technology and
science is catching up -- and over the next decades we will
see wizards increasingly find ways of building distributed
technology that will be as economical as centralized
technology but will be far more responsive, and flexible.

When the three come converge, the wizard, prophet and
backer, it will trigger an distributed industrial
revolution.  That process is well underway -- CRISPER, dirt
cheap genome encoding, artificial intelligence, robotics,
nano-tech and materials science are all heading towards that
convergence.


** A Preface for Collapse

#+begin_quote
I set out now
in a box apon the sea

— Maximus Poems
  Charles Olson
#+end_quote

The collapse is already underway, and as in all things, it
isn't evenly distributed. 




* The Rest

** The Yellow Brick Road: a manifesto

  - [[./manifesto-yellow.org][The Yellow Brick Road]] (draft)
  - [[./manifesto-window.org][Window]]

-----

  - a preface for the collapse
  - the accidental apex predator
  - the nature of human scale
  - the nature of change
  - carrying capacities
  - the inevitable
  - the window

-----

The collapse is already well underway, but as in all things,
it isn't evenly distributed.


All is process, not in thing.

Everything is in the process of becoming something else


People are surprised at how suddenly societies collapse,

The decline had been long and clear, and yet unseen

we normalize gradual change, adjusting incrementally, and
seldom notice anything below the threshold when biological
alarms are triggered.  And when that tipping point occurs,
we go along with the madness and most of us go both
collectively and individually insane.

burn books, rat out your neighbor to the death squads, march
and chant abominations, cheer and jeer at public executions
and unhinged pledges of hate, and fear, and stupidity.  You
shake your head, thinking that you could never do such
things, but you will, most of us will.  /That/ is normal,
it's the one's who don't who are the outliers. This is the
monstrous darkness that lies within our souls and there is
no getting around it.  Welcome to the collapse, you are in
good company.




mobs are herds for humans, where we turn off the cerebral
cortex and let our limbic systems ride roughshod.



it was happening all around them and they never seem to see

normalization


hope is not given, its germinated, nurtured, and protected

fragile, 


  corn rust?  should have wiped out north america, and it
  was only through the heroic efforts of xxx that averted it
  -- but his success fixed a short term problem that didn't
  allow farmers to understand or fix the root problem of
  monoculture and factory farming -- top-soil depletion,
  over-use of pesticides and nitrogen-based fertilizers,
  reduction of interdependent diverse crops adapted to
  different biomes and climatic conditions with a wealth of
  genetic information to a handful of plants, insects and
  animals.  he only found that answer because of the
  enormous varieties of corn in the Americas -- same can be
  said for the potato -- that storehouse of generic
  information is vanishing before us in real time.

  while pitting the wizard against the prophet makes for a
  good story -- the approach of the wizard boils down to
  fixing human problems by scaling things and using up
  resources in unsustainable ways.  They forstall the
  inevitable day when it's all used up, rather than doing
  the really hard job of building sustainable food
  production systems.  and the only people that seem to be
  complaining about this are little better by also trying to
  take away the wizard's toll-chain that is the only way
  that sustainable food production at scale could be
  achieved -- the anti-GMO people seem to be saying, let's
  trigger a major human die-off -- because GMO is the only
  path forward that can avert that from happening.  Leaving
  natural selection to chance, or the ancient equivilent of
  that process which is cross breeding and singling out
  useful traits in plants and animals -- which is basically
  simply accelerates natural selection of successful
  mutations.  Doing the same thing orders of magnitude
  faster in a lab, where it's clear what is happening and
  what is being altered, for some reason, scares the only
  people who seem to be motivated to fix monoculture
  food-production.


  imply put, monoculture farming is an intentional
  unsustainable positive-feedback loop

the fix would not be painful -- but would require people to
make fundemental changes in their relationship to food and
expectations of food availability -- people don't rewire
deeply ingrained habits unless they are forced to -- the
food industry won't let that happen, and the won't allow
government to make the changes needed to fix things.  Short
of the collapse of the present food production system 

people think they can change the system by making lifestyle
choices which the food industry has co-opted and turned into
an extension of monoculture production methods.

as bill mollison said, it all starts at the doorstep, if you
have weeds at your doorstep you have weeds throughout your
farm.




the young are blinded by death that they can only percieve
as a horizon, forever receding as they approach

the old are blinded by certain death that looms larger with
every sunset, that they can feel in their bones.  they might
have a longer perspective than the young, living
increasingly at lower-slower pace-layers, allowing them to
shepard institutions and processes that they eventually pass
on to the next generation as they slide into their shoes.

This is quickly becoming untennable, as the rate of change
increases so quickly that even the old are unable to master
it long enough to get a handle on it -- there simply is no
longer the time afforded by the slower pace-layers.

the rallying cry from the counter-culture movement in the
early '70's 'don't trust anyone over thirty' hasn't worked
out very well, with college sophmores wreaking wholesale
destruction of the social fabric -- and not to make the
world better, but just to make a buck

I used to be up their on the virtual baracades, cheering on
such efforts, not understanding that you can't build a
civilization in happhazed never-look-back of the
fashion-layer alone.  Civilization is bigger than any of us,
a slow AI that in one sense we are aware of being part of,

  there are something that should not be mucked with,
  because whenever Man has done so in the past, the results
  have been most unpleasant.

the young turks stormed the Bastille and proceeded to
indiscriminately slaughter anyone in their way.  The
Newspaper, and Television News, Library Science, the family
as an atomic social institution is being replaced by loners
who systematically cut themselves off from human contact --
food is either eaten out, or delivered -- and the few who
think they cook are actually buying meal kits -- the latest
iteration on Betty Crocker's social hack of getting
housewifes who felt guilty at cheating when buying a
cake-mix by having them to add an egg.  Lipton chicken
noodle soup -- 'is it soup yet' used the same trick except
the 'cook' needed to boil water.  Now meal kits from
companies like Blue Apron are doing the same thing by
requiring people to know how to light a gas-ring, and stir
the contents of different packets and sachetes into a pot at
proscribed intervals.

everything has devolved into lifestyle choices which reflect
whatever 'identity' a person happens to choose -- such
identites are little more than fads and exclusionary
ideologies.  the bigoted seneseless cruelty of the social
justice warriors and the train wreck done to feminism --
 and several generations of women who
sacrificed them selves for the right to vote and the world
changing change in the 20th century to the workplace and
reproductive health and rights

Eleanor Roosevelt would be horrified at what the feminist
movement has become.  Just as Teddy Roosevelt would be
equally horrified at both what the green movement borne from
a common sense approach of conserving, sheparding and and
protecting natural ecosystems and resources as well as the
utter depravity of those calling themselves conservatives
but seemingly unaware of what it means to conserve.


In fifty years time, we will look back at America and
recognize that it begun to decline the day that the Berlin
Wall came down and that outright collapse began only a
decade later.  The deplorable state of the nation who has
abandoned eduction, healthcare, and embrased mass
incarceration, a militarized police force, legal
prescription optiate addiction for proft, hyper
partisianship and a disfunctional federal government, all
amplified and egged on by the billianare social network
mavens for profit.


From outside it's easy to shake one's head and watch America
rip itself apart and destroy itself for no desernable
reason.  Why would the richest country, founded on the
promise of fairness and freedom do that to itself? All the
while not understanding that American won't be content to
self-immolate, they are intent on dragging the rest of the
world down with them as they rush export it all wholesale to
be leveraged by deplorable governmants as weapons wielded
against their own citizens to retain power and profit, and
polluting functioning societies throughout the rest of the
world.

Food as as a reflection of culture religion,
has been replaced as food as an packaged-ideology with about
as much credibility as any religious dietary restriction --
the folks that coopted the original organic food movement,
the vegitarians who weren't ideologically pure enough for
some who dreamed up veganism out of thin air, and hovering
above all of them, the pall of the anti-gmo movement who
built a belief system based on fear, misinformation and
outright stupidity.  then there are the  

they didn't even try to replace them, they just wiped them
out without understand that the roles they played were
cornerstone of the functional civilization

smart mobs, folksonomies, the social graph -- suddenly the
cloud was where everything was and nothing could be counted
on to still be around next week



but today, with change happening so fast, that
perspective has slipped away and they no longer have any
skin in the game.


------

The manifesto should be short and as Golem would say,
juicy-sweet, as good manifestos should always be.  

And then backed up by additional in-depth texts.

So now that we aren't burdened with telling an origin story
in the manifesto, we can focus on laying out the single more
important problem and the only solution to that problem.

----

The Accidental Apex Predator


Man is an outlier

 circumstantial outliers


Man is the planet's apex predator -- we weren't meant to be
apex predator, we're designed to be in the middle.  The
problem is that we became an apex predator that the
ecosystem didn't have time to evolve any checks and balances
to keep us under control.  Apex predators are supposed to be
a relatively small niche in any ecosystem.  It's an
important niche, but it doesn't require many to get the job
done.  Man turned that on it's head.  Man has managed to
thwart every natural check on our population growth that
nature as thrown at us, creating a highly adaptable,
resilient positive feedback loop which has engulfed the
planet.  Ecological collapse, pandemics, drought, crop
failures, nothing seems to stop Man's runaway train.  So now
nature is gearing up to deploy the nuclear option -- global
climate change which will continue to get worse until Man
has shrunk back to within the planet's carrying capacity or
Man is effectively extinct.  It might take hundreds of
thousand or even millions of years for the planet's
biosphere to recover from what we've done, but it will
happen.

But there is another way.  We need to engineer checks and
balances on ourselves that overcome our cognitive and
biological shortcomings.  This is not as draconian or
dramatic as it might sound.  This is where the lower
pace-layers come into play -- we need to give the same
technoligical and cognitive advantage that we hold at human
scales to processes that are happening at ROCs that are
below human cognitive limits.  The slower pace-layers put
the brakes on the faster layers to ensure they don't go out
of control.  Man has bipassed those slower processes.  We
need to put them back into power.

This is where Slow AI comes in.


Humans don't scale, we don't scale physically -- the attack
of the 50 foot woman not withstanding -- we don't scale
cognitively and we don't scale socially.

JBS Haldane's essay, "On Being the Right Size" cite:haldane:1928being

We are pack animals we specialize, adapt, and cooperate.

There are animals who do scale, herd (large herbavores),
flock (some bird species) and school (some fish species)
animals scale by cooperating but do not specialize.  Packs
are designed to be small, fast and adaptable to that they
can counter the collective strength of herds.  Packs attack
herds.  Herds work in the aggregate, the survival of
individuals is not important.  In fact herds are designed
for the weak members to be sacrificed so that the stronger
members can surive.

Herds, flocks and schools work because individuals in the
group are interchangable.  This does not mean they are
equal, but they are interchangable.  

Packs have leaders, there are always power imbalances within
packs, but if the pack stays small those power imbalances
are largely compensated for by the other members of the
pack.

When you try to scale a pack, those power imbalances are
amplified and the larger the group the larger the power, and
later wealth imbalances become.

The most important thing to emerge from large packs is
slavery.  Slavery started when Man became sedentary and
stayed in one place year round.  When this happened, the
concept of territory that was loosely controlled by a pack.
Territories overlap with other packs and conflicts between
packs resulted in resolving territorial borders.  These
conflicts were short and violent but seldom rose above what
we would consider to be a raid, or a skirmish today.

When we became sedantary this concept of change evolved into
the idea of land as property that can be owned by
individuals within a pack.  In most cases this meant that
land was owned by a few, and everyone else had lesser land
holdings or had to provide services, goods and later wealth
to those in power who held that land.

Land ownership went hand in hand with the idea of ownership
of anything physical, including tools, dwellings, clothing
and food and water.  It's no accident that we use the same
word, property to include land, physical goods, food and
most recently, information.

You can't scale human groups without it resulting in slavery
and property of a small group of elites.  Elites hoard
things for their own benifit, and will only share with
others when they see a return on their expenditure.

The thing is though, that without those two things, slavery
and property we would not have civilization, the arts,
science, philosophy or advanced technology.

Slavery produces surpluses that allow a small number of
people in a society to be able to pursue intellectual
pursuits and all advances have come from having enough
resources for some people to spend some of their time doing
things that are not directly connected to immediate
survival.

Ah, I hear some of you say, but we have advanced and no
longer have institutionalized slavery.  But we do, we just
don't call it that any more.

Toffler

 - physical force -> physical wealth -> symbolic wealth -> knowledge
 - slave/convict  -> indenture/serf/conscript -> employee
 - tools -> machines -> cognitive machines -- robots, which
   are computers controlling machines.

When cognitive machines become semi-autonomous and self
directing, they become capable of taking the place of
slaves.

This is a step in the right direction but will not erase
power/wealth imbalances because there will always be a
scarcity of land as property.  So long as humans try to
scale packs to the size of herds it is not possible to build
egalitarian societies.

Cognitive machine-slaves are not enough:

  - first, we need to go the next step and replace the
    functions of the elites with cognitive machines as well.

  - second, we need to turn into a world of large
    centralized nation-states into a world of distributed,
    confederated network of packs.

The network that ties all of the packs together needs to be
a trustless system that ensures a even playing field for all
packs so that the system doesn't devolve back into a
herd slave-states again.



After we do this, a lot of things will begin to self-correct
over the next couple of centuries.

  - educated women and low infant mortality will eventually
    shrink the population within the planet's carrying
    capacity

  - machine cog will make it possible to convert slaves into
    the thinking class -- and the thinking class is who
    drives innovation and solves problems -- this will help
    maintain the rate of change long enough to solve really
    big problems like how to keep alive until our population
    is under control, and how to keep our climate from going
    off the skids.

    in effect machine-cog, when used right, can be used to
    create negative feedback loops that will keep Man from
    falling back into the positive feedback loop we are in
    now and that will destroy us if we don't find a way to
    stop.

  - we spread throughout the solar system -- there are
    enough natural resources in the solar system to support
    tens of thousands of earths at a far higher standard of
    living than we have today -- we can't do this without
    moving our industry and resource aquisition off planet. 
    Achieving a post-scarcity civilization depends on this
    -- if we don't, the finite natural resources on our
    planet will ensure that there will be power and wealth
    imbalances.

Is this a utopian vision?  Hell no. There will still be
suffering and misery and the benifits will be far from
evenly distributed.  The Universe works on scales in which
we aren't even rounding errors.  The Universe doesn't need
us or even notice us and we will never be in a position to
change that.  Closer to home Life is messy, brutal and
unfair.  And if it wasn't then Life would eventually
stagnate and die.  Man is no different, without challenges
and adversity we too will either stagnate and die or as we
are doing now, will grow fat and bored and stupid and spend
all of our time doing things that will wipe ourselves out.

The most important thing to do is stop being scared, stop
listening to those who are making you scared as a means of
tricking you into enslaving yourself to them.  Next, you
don't deserve anything, you have no rights to anything that
you don't earn.  And you can't do anything unless you have
the cognitive tools to know when people are selling you the
Brookline Bridge.  Learn how to learn and keep learning even
with your dieing breath.  You think you don't need to know
how to think?  That is the definition of stupidity.  And
stupid people will get screwed over, every single time.  So
you need to arm yourself to the teeth.  And only the stupid
think that means guns or knives.  Physical force is the
crudest and least effective way of protecting yourself.
Knowledge and the tools to know how to wield that knowledge
is.

Finally, get off your ass and do something, anything no
matter how small to make the world better for your children.
It's too late for us to reach the promised land, but if we
try hard enough, then maybe they will live to see it.


The message is the mantra which is don't scale: distribute,
conferderate, cooperate.

   Oh, and be excellent to one another

-----

Mobs



-----

The draft linked above is origin story -- that's what
tripped me up -- move origin story to the primer -- at the
beginning -- which is the foundation and framework for
education, governance and culture.

The origin story will be told from three POV -- Big History
is LOD the linear narrative that starts big and drills down
small -- a story with a beginning middle and end.  Next will
be Scopic -- with pace layers with different ROCs.  Now I
said three but perhaps those two are enough.  But if there
is a third it is Process, our origin as a continual process
of becoming something else.  Each POV is a very different
perspective giving a different understanding of our origin
and who we are.  There is no one right way -- and each of us
construct our own origin story as a combination of parts of
these three and countless others.  Each POV is an map which
is a filter used to fit something large and complex into our
poor limited minds.  The most powerful thing about maps is
that they don't have much information, they are designed to
show patterns in complexity -- Ariadne's thread that leads
us through the labryinth -- which means as Umberto Eco said,
that you don't need the Minotaur in the middle, he's just
thrown in to make things a bit more
exciting. cite:eco:1986semiotics p.80

I've been thinking about the primer all wrong -- it's not an
instruction manual -- it's a bible, an encyclopedic skeleton
key which you use to unlock everything in the /hoard/ and
/arc/.

w&w is the primer for the primer -- appl is a generative
framework for the hoard and the arc is simply everything
else -- everything.

---

Humility

above all else we need to instill a deep ingrained sense of
humility.

that is number one -- no one is lower than anyone else, all
things apply to all of us the same no exceptions.

fuck elites -- that's something the Buddhists understand,
muck to muck -- the greatest leaders all had that sense of
humility.

Social Contract

So what's the new social contract?  



  - [[./manifesto-filters.org][Filters]]

  - [[./manifesto-life.org][Life]]

 - Roadmap [[./roadmap-overview.org][Overview]] 

  - [[./manifesto-savannah.org][Savannah]]
  - [[./manifesto-cognition.org][Cognition]]
  - [[./manifesto-polis.org][Polis]]
  - [[./manifesto-fragility.org][Fragility]]
  - [[./manifesto-estrangement.org][Estrangement]]
  - [[./manifesto-social.org][Social]]
  - [[./manifesto-natures.org][Natures]]
  - [[./manifesto-storms.org][Storms]]
  - [[./manifesto-maps.org][Maps]]
  - [[./manifesto-stories.org][Stories]]
