#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Manifesto | TOC

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Manifesto | Table of Contents
:PROPERTIES:
:CUSTOM_ID:
:Name:      /home/deerpig/proj/chenla/manifesto/index.org
:Created:   2017-10-06T18:08@Prek Leap (11.642600N-104.919210W)
:ID:        730bbfc9-e0cb-4c6f-97e0-4dbdef81b4d9
:VER:       560560166.539684901
:GEO:       48P-491193-1287029-15
:BXID:      proj:TWT0-8431
:Class:     primer
:Entity:    toc
:Status:    wip 
:Licence:   MIT/CC BY-SA 4.0
:END:


#+begin_quote
I have to learn the simplest things 
last.  Which made for difficulties.
Even at sea I was slow, to get the hand out, or to cross
a wet deck.
            The sea was not, finally, my trade
But even my trade, at it, I stood estranged
from that which is most familiar.  Was delayed,
and not content with the man's argument
that such a postponement
is now the nature of 
obedience.
              that we are all late
              in a slow time,
              that we grow up many
              And the single
              is not easily
              known


-- Maximus, to himself
   Charles Olson  
#+end_quote


** The Yellow Brick Road: a manifesto

  - [[./manifesto-yellow.org][The Yellow Brick Road]] (draft)
  - [[./manifesto-window.org][Window]]

-----

  - a preface for the collapse
  - the accidental apex predator
  - the nature of human scale
  - the nature of change
  - carrying capacities
  - the inevitable
  - the window

-----

The collapse is already well underway, but as in all things,
it isn't evenly distributed.


All is process, not in thing.

Everything is in the process of becoming something else


People are surprised at how suddenly societies collapse,

The decline had been long and clear, and yet unseen

we normalize gradual change, adjusting incrementally, and
seldom notice anything below the threshold when biological
alarms are triggered.  And when that tipping point occurs,
we go along with the madness and most of us go both
collectively and individually insane.

burn books, rat out your neighbor to the death squads, march
and chant abominations, cheer and jeer at public executions
and unhinged pledges of hate, and fear, and stupidity.  You
shake your head, thinking that you could never do such
things, but you will, most of us will.  /That/ is normal,
it's the one's who don't who are the outliers. This is the
monstrous darkness that lies within our souls and there is
no getting around it.  Welcome to the collapse, you are in
good company.




mobs are herds for humans, where we turn off the cerebral
cortex and let our limbic systems ride roughshod.



it was happening all around them and they never seem to see

normalization


hope is not given, its germinated, nurtured, and protected

fragile, 


  corn rust?  should have wiped out north america, and it
  was only through the heroic efforts of xxx that averted it
  -- but his success fixed a short term problem that didn't
  allow farmers to understand or fix the root problem of
  monoculture and factory farming -- top-soil depletion,
  over-use of pesticides and nitrogen-based fertilizers,
  reduction of interdependent diverse crops adapted to
  different biomes and climatic conditions with a wealth of
  genetic information to a handful of plants, insects and
  animals.  he only found that answer because of the
  enormous varieties of corn in the Americas -- same can be
  said for the potato -- that storehouse of generic
  information is vanishing before us in real time.

  while pitting the wizard against the prophet makes for a
  good story -- the approach of the wizard boils down to
  fixing human problems by scaling things and using up
  resources in unsustainable ways.  They forstall the
  inevitable day when it's all used up, rather than doing
  the really hard job of building sustainable food
  production systems.  and the only people that seem to be
  complaining about this are little better by also trying to
  take away the wizard's toll-chain that is the only way
  that sustainable food production at scale could be
  achieved -- the anti-GMO people seem to be saying, let's
  trigger a major human die-off -- because GMO is the only
  path forward that can avert that from happening.  Leaving
  natural selection to chance, or the ancient equivilent of
  that process which is cross breeding and singling out
  useful traits in plants and animals -- which is basically
  simply accelerates natural selection of successful
  mutations.  Doing the same thing orders of magnitude
  faster in a lab, where it's clear what is happening and
  what is being altered, for some reason, scares the only
  people who seem to be motivated to fix monoculture
  food-production.


  imply put, monoculture farming is an intentional
  unsustainable positive-feedback loop

the fix would not be painful -- but would require people to
make fundemental changes in their relationship to food and
expectations of food availability -- people don't rewire
deeply ingrained habits unless they are forced to -- the
food industry won't let that happen, and the won't allow
government to make the changes needed to fix things.  Short
of the collapse of the present food production system 

people think they can change the system by making lifestyle
choices which the food industry has co-opted and turned into
an extension of monoculture production methods.

as bill mollison said, it all starts at the doorstep, if you
have weeds at your doorstep you have weeds throughout your
farm.




the young are blinded by death that they can only percieve
as a horizon, forever receding as they approach

the old are blinded by certain death that looms larger with
every sunset, that they can feel in their bones.  they might
have a longer perspective than the young, living
increasingly at lower-slower pace-layers, allowing them to
shepard institutions and processes that they eventually pass
on to the next generation as they slide into their shoes.

This is quickly becoming untennable, as the rate of change
increases so quickly that even the old are unable to master
it long enough to get a handle on it -- there simply is no
longer the time afforded by the slower pace-layers.

the rallying cry from the counter-culture movement in the
early '70's 'don't trust anyone over thirty' hasn't worked
out very well, with college sophmores wreaking wholesale
destruction of the social fabric -- and not to make the
world better, but just to make a buck

I used to be up their on the virtual baracades, cheering on
such efforts, not understanding that you can't build a
civilization in happhazed never-look-back of the
fashion-layer alone.  Civilization is bigger than any of us,
a slow AI that in one sense we are aware of being part of,

  there are something that should not be mucked with,
  because whenever Man has done so in the past, the results
  have been most unpleasant.

the young turks stormed the Bastille and proceeded to
indiscriminately slaughter anyone in their way.  The
Newspaper, and Television News, Library Science, the family
as an atomic social institution is being replaced by loners
who systematically cut themselves off from human contact --
food is either eaten out, or delivered -- and the few who
think they cook are actually buying meal kits -- the latest
iteration on Betty Crocker's social hack of getting
housewifes who felt guilty at cheating when buying a
cake-mix by having them to add an egg.  Lipton chicken
noodle soup -- 'is it soup yet' used the same trick except
the 'cook' needed to boil water.  Now meal kits from
companies like Blue Apron are doing the same thing by
requiring people to know how to light a gas-ring, and stir
the contents of different packets and sachetes into a pot at
proscribed intervals.

everything has devolved into lifestyle choices which reflect
whatever 'identity' a person happens to choose -- such
identites are little more than fads and exclusionary
ideologies.  the bigoted seneseless cruelty of the social
justice warriors and the train wreck done to feminism --
 and several generations of women who
sacrificed them selves for the right to vote and the world
changing change in the 20th century to the workplace and
reproductive health and rights

Eleanor Roosevelt would be horrified at what the feminist
movement has become.  Just as Teddy Roosevelt would be
equally horrified at both what the green movement borne from
a common sense approach of conserving, sheparding and and
protecting natural ecosystems and resources as well as the
utter depravity of those calling themselves conservatives
but seemingly unaware of what it means to conserve.


In fifty years time, we will look back at America and
recognize that it begun to decline the day that the Berlin
Wall came down and that outright collapse began only a
decade later.  The deplorable state of the nation who has
abandoned eduction, healthcare, and embrased mass
incarceration, a militarized police force, legal
prescription optiate addiction for proft, hyper
partisianship and a disfunctional federal government, all
amplified and egged on by the billianare social network
mavens for profit.


From outside it's easy to shake one's head and watch America
rip itself apart and destroy itself for no desernable
reason.  Why would the richest country, founded on the
promise of fairness and freedom do that to itself? All the
while not understanding that American won't be content to
self-immolate, they are intent on dragging the rest of the
world down with them as they rush export it all wholesale to
be leveraged by deplorable governmants as weapons wielded
against their own citizens to retain power and profit, and
polluting functioning societies throughout the rest of the
world.

Food as as a reflection of culture religion,
has been replaced as food as an packaged-ideology with about
as much credibility as any religious dietary restriction --
the folks that coopted the original organic food movement,
the vegitarians who weren't ideologically pure enough for
some who dreamed up veganism out of thin air, and hovering
above all of them, the pall of the anti-gmo movement who
built a belief system based on fear, misinformation and
outright stupidity.  then there are the  

they didn't even try to replace them, they just wiped them
out without understand that the roles they played were
cornerstone of the functional civilization

smart mobs, folksonomies, the social graph -- suddenly the
cloud was where everything was and nothing could be counted
on to still be around next week



but today, with change happening so fast, that
perspective has slipped away and they no longer have any
skin in the game.


------

The manifesto should be short and as Golem would say,
juicy-sweet, as good manifestos should always be.  

And then backed up by additional in-depth texts.

So now that we aren't burdened with telling an origin story
in the manifesto, we can focus on laying out the single more
important problem and the only solution to that problem.

----

The Accidental Apex Predator


Man is an outlier

 circumstantial outliers


Man is the planet's apex predator -- we weren't meant to be
apex predator, we're designed to be in the middle.  The
problem is that we became an apex predator that the
ecosystem didn't have time to evolve any checks and balances
to keep us under control.  Apex predators are supposed to be
a relatively small niche in any ecosystem.  It's an
important niche, but it doesn't require many to get the job
done.  Man turned that on it's head.  Man has managed to
thwart every natural check on our population growth that
nature as thrown at us, creating a highly adaptable,
resilient positive feedback loop which has engulfed the
planet.  Ecological collapse, pandemics, drought, crop
failures, nothing seems to stop Man's runaway train.  So now
nature is gearing up to deploy the nuclear option -- global
climate change which will continue to get worse until Man
has shrunk back to within the planet's carrying capacity or
Man is effectively extinct.  It might take hundreds of
thousand or even millions of years for the planet's
biosphere to recover from what we've done, but it will
happen.

But there is another way.  We need to engineer checks and
balances on ourselves that overcome our cognitive and
biological shortcomings.  This is not as draconian or
dramatic as it might sound.  This is where the lower
pace-layers come into play -- we need to give the same
technoligical and cognitive advantage that we hold at human
scales to processes that are happening at ROCs that are
below human cognitive limits.  The slower pace-layers put
the brakes on the faster layers to ensure they don't go out
of control.  Man has bipassed those slower processes.  We
need to put them back into power.

This is where Slow AI comes in.


Humans don't scale, we don't scale physically -- the attack
of the 50 foot woman not withstanding -- we don't scale
cognitively and we don't scale socially.

JBS Haldane's essay, "On Being the Right Size" cite:haldane:1928being

We are pack animals we specialize, adapt, and cooperate.

There are animals who do scale, herd (large herbavores),
flock (some bird species) and school (some fish species)
animals scale by cooperating but do not specialize.  Packs
are designed to be small, fast and adaptable to that they
can counter the collective strength of herds.  Packs attack
herds.  Herds work in the aggregate, the survival of
individuals is not important.  In fact herds are designed
for the weak members to be sacrificed so that the stronger
members can surive.

Herds, flocks and schools work because individuals in the
group are interchangable.  This does not mean they are
equal, but they are interchangable.  

Packs have leaders, there are always power imbalances within
packs, but if the pack stays small those power imbalances
are largely compensated for by the other members of the
pack.

When you try to scale a pack, those power imbalances are
amplified and the larger the group the larger the power, and
later wealth imbalances become.

The most important thing to emerge from large packs is
slavery.  Slavery started when Man became sedentary and
stayed in one place year round.  When this happened, the
concept of territory that was loosely controlled by a pack.
Territories overlap with other packs and conflicts between
packs resulted in resolving territorial borders.  These
conflicts were short and violent but seldom rose above what
we would consider to be a raid, or a skirmish today.

When we became sedantary this concept of change evolved into
the idea of land as property that can be owned by
individuals within a pack.  In most cases this meant that
land was owned by a few, and everyone else had lesser land
holdings or had to provide services, goods and later wealth
to those in power who held that land.

Land ownership went hand in hand with the idea of ownership
of anything physical, including tools, dwellings, clothing
and food and water.  It's no accident that we use the same
word, property to include land, physical goods, food and
most recently, information.

You can't scale human groups without it resulting in slavery
and property of a small group of elites.  Elites hoard
things for their own benifit, and will only share with
others when they see a return on their expenditure.

The thing is though, that without those two things, slavery
and property we would not have civilization, the arts,
science, philosophy or advanced technology.

Slavery produces surpluses that allow a small number of
people in a society to be able to pursue intellectual
pursuits and all advances have come from having enough
resources for some people to spend some of their time doing
things that are not directly connected to immediate
survival.

Ah, I hear some of you say, but we have advanced and no
longer have institutionalized slavery.  But we do, we just
don't call it that any more.

Toffler

 - physical force -> physical wealth -> symbolic wealth -> knowledge
 - slave/convict  -> indenture/serf/conscript -> employee
 - tools -> machines -> cognitive machines -- robots, which
   are computers controlling machines.

When cognitive machines become semi-autonomous and self
directing, they become capable of taking the place of
slaves.

This is a step in the right direction but will not erase
power/wealth imbalances because there will always be a
scarcity of land as property.  So long as humans try to
scale packs to the size of herds it is not possible to build
egalitarian societies.

Cognitive machine-slaves are not enough:

  - first, we need to go the next step and replace the
    functions of the elites with cognitive machines as well.

  - second, we need to turn into a world of large
    centralized nation-states into a world of distributed,
    confederated network of packs.

The network that ties all of the packs together needs to be
a trustless system that ensures a even playing field for all
packs so that the system doesn't devolve back into a
herd slave-states again.



After we do this, a lot of things will begin to self-correct
over the next couple of centuries.

  - educated women and low infant mortality will eventually
    shrink the population within the planet's carrying
    capacity

  - machine cog will make it possible to convert slaves into
    the thinking class -- and the thinking class is who
    drives innovation and solves problems -- this will help
    maintain the rate of change long enough to solve really
    big problems like how to keep alive until our population
    is under control, and how to keep our climate from going
    off the skids.

    in effect machine-cog, when used right, can be used to
    create negative feedback loops that will keep Man from
    falling back into the positive feedback loop we are in
    now and that will destroy us if we don't find a way to
    stop.

  - we spread throughout the solar system -- there are
    enough natural resources in the solar system to support
    tens of thousands of earths at a far higher standard of
    living than we have today -- we can't do this without
    moving our industry and resource aquisition off planet. 
    Achieving a post-scarcity civilization depends on this
    -- if we don't, the finite natural resources on our
    planet will ensure that there will be power and wealth
    imbalances.

Is this a utopian vision?  Hell no. There will still be
suffering and misery and the benifits will be far from
evenly distributed.  The Universe works on scales in which
we aren't even rounding errors.  The Universe doesn't need
us or even notice us and we will never be in a position to
change that.  Closer to home Life is messy, brutal and
unfair.  And if it wasn't then Life would eventually
stagnate and die.  Man is no different, without challenges
and adversity we too will either stagnate and die or as we
are doing now, will grow fat and bored and stupid and spend
all of our time doing things that will wipe ourselves out.

The most important thing to do is stop being scared, stop
listening to those who are making you scared as a means of
tricking you into enslaving yourself to them.  Next, you
don't deserve anything, you have no rights to anything that
you don't earn.  And you can't do anything unless you have
the cognitive tools to know when people are selling you the
Brookline Bridge.  Learn how to learn and keep learning even
with your dieing breath.  You think you don't need to know
how to think?  That is the definition of stupidity.  And
stupid people will get screwed over, every single time.  So
you need to arm yourself to the teeth.  And only the stupid
think that means guns or knives.  Physical force is the
crudest and least effective way of protecting yourself.
Knowledge and the tools to know how to wield that knowledge
is.

Finally, get off your ass and do something, anything no
matter how small to make the world better for your children.
It's too late for us to reach the promised land, but if we
try hard enough, then maybe they will live to see it.


The message is the mantra which is don't scale: distribute,
conferderate, cooperate.

   Oh, and be excellent to one another

-----

Mobs



-----

The draft linked above is origin story -- that's what
tripped me up -- move origin story to the primer -- at the
beginning -- which is the foundation and framework for
education, governance and culture.

The origin story will be told from three POV -- Big History
is LOD the linear narrative that starts big and drills down
small -- a story with a beginning middle and end.  Next will
be Scopic -- with pace layers with different ROCs.  Now I
said three but perhaps those two are enough.  But if there
is a third it is Process, our origin as a continual process
of becoming something else.  Each POV is a very different
perspective giving a different understanding of our origin
and who we are.  There is no one right way -- and each of us
construct our own origin story as a combination of parts of
these three and countless others.  Each POV is an map which
is a filter used to fit something large and complex into our
poor limited minds.  The most powerful thing about maps is
that they don't have much information, they are designed to
show patterns in complexity -- Ariadne's thread that leads
us through the labryinth -- which means as Umberto Eco said,
that you don't need the Minotaur in the middle, he's just
thrown in to make things a bit more
exciting. cite:eco:1986semiotics p.80

I've been thinking about the primer all wrong -- it's not an
instruction manual -- it's a bible, an encyclopedic skeleton
key which you use to unlock everything in the /hoard/ and
/arc/.

w&w is the primer for the primer -- appl is a generative
framework for the hoard and the arc is simply everything
else -- everything.

---

Humility

above all else we need to instill a deep ingrained sense of
humility.

that is number one -- no one is lower than anyone else, all
things apply to all of us the same no exceptions.

fuck elites -- that's something the Buddhists understand,
muck to muck -- the greatest leaders all had that sense of
humility.

Social Contract

So what's the new social contract?  


** The Warp and Woof

#+begin_quote
1. warp and woof(Noun)

   The threads in a woven fabric, comprised of the warp
   (threads running lengthwise) and woof (threads running
   crosswise) to create the texture of the fabric.

2. warp and woof(Noun)

   The fundamental structure of any process or system.

— [[http://www.definitions.net/definition/warp%20and%20woof][warp and woof]] | definitions.net
— [[https://en.wiktionary.org/wiki/warp_and_woof][warp and woof]] | Wiktionary
#+end_quote

This is not an origin story -- that's moved to the primer.

Part 1: Three Point of Views

The premise is that it is helpful to always understand the Point
of View (POV) -- or perspective that you are looking at
something because when you change your POV you change the
context of what you are seeing and will often see things you
didn't see before, or even see things in a completely
different way than you saw before.

We define three different perspectives:

  - LOD : Level of Detail
  - ROC : Rate of Change
  - POC : Process of Change

These three POVs form the foundation for how everything else
*everything* in APPL, Primer & Hoard are understood.

Each POV becomes increasingly more complex and abstract, but
each builds on the one before and let's you see the same
thing from a different perspective.  It does not negate the
other POVs so much as enriches them and provides a more
powerful toolbox for modeling and understanding.

For example, let's look at the Origin Story that will start
the Primer.

The Origin LOD is basically Big History -- a linear timeline
with a beginning (big bang) middle (from BB to now) and the
end (projected heat death of the universe).  The narrative
is organized around tipping points where complexity reaches
a critical mass that changes the nature of the universe, and
then later life on earth and eventually us.  This is a
fantastic narrative and is a perfect way of easing people
into the origin story which can be understood like any other
origin story.

The Origin ROC is basically a finer grained version of Big
History that uses the concept of causal propagation (think
Light Cones) to understand that different things change at
different speeds and that all of these things are mixed
together.  It's the embodiment of Gibson's the future is
already here isn't just not evenly distributed.  Brand's
Pace-Layers is a good way of understanding this, as well as
Light Cones and causal propagation of change happening at
the speed of light but making the point that the speed of
light is the maximum speed that things can propagate, most
things are propagating far slower.

The Origin POC is still a little unclear -- but I think that
it will basically boil down to how when we talk about LOD
and ROC we are talking about substance (as the term is used
in philosophy) that from the time of Aristotle has claimed
as the only way to understand and argue about the world.
Sustance changes over time, but that change is accidental
and does not change form so that it still remains
essentially the same thing.  But things can also be thought
of as processes that are in a constant state of changing and
becoming something else.  The NYC as substance assumes that
it may change over time but it is still the same NYC from
when it was a small settlement called New Amsterdam till
today.  Process philosophy argues that it is not the same
city even from one moment to the next -- ala you can never
step in the same river twice.  So when you compare POC with
ROC you are considering not only how fast things change, but
the substance of how substances transform over time.
Understanding things as process and that things change over
time to become completely different things is important --
we tend to use words, events and historical figures as if
they were contemporaries from our own present understanding
of the world -- they were not what we think of them today --
we have reinvented them and are continually reinventing
everything around us -- history is what is written -- what
was said -- which is a moving target as we write new things.
The past is not a static fixed thing because out
understanding is not a static fixed thing.  This is
important in so many different areas.  For example, in USA,
when people argue that interpretation of the constitution
must be in done as it was intended when it was written in
the 18th century.  Is this even possible?  We can not know
what their original intend was because our understanding of
what we think their original intent was is constantly
changing.  The past is always an invention of the present.
This does not mean that it's not important to strive to
understand what that original intent is, it's just that our
understanding is changing and will never stop changing,
which in some respects negates the original intention of
what we set out to do in the first place.  POC has enormous
implications for everything from contracts to education to
agriculture to business.

Taken together these three models will give us a set of
powerful tools for understanding, planning, building, and
maintaining civilizations.


** APPL
:PROPERTIES:
:ID:       9527a3d3-2034-4f0d-acf4-7ba4fb05723c
:END:

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.

APL was divided into three parts, Towns, Buildings and
Construction.  But APL is a pattern language for
architecture and buildings.  For this to work it had to
define many patterns that more properly belonged to urban
planning, culture and governance though these were patterns
that supported the construction of beautiful buildings.

Our pattern language has a far broader scope; building an
antifragile civilization for mankind.  It is such a broad,
and ambitious scope that it borders on hubris.  After all we
barely agree on what civilization is, let alone how to build
one from first principles.  Though the undertaking is
assuredly fated to fall far short of it's goals, it is
important to instigate a tradition of people and
institutions to try.  Over many generations such
investigations could well become the foundation for and
roadmap for our survival and hopefully, prosperity.

But if Mankind is to become antifragile, we must become as
distributed as possible.  That means, among other things we
need to be thinking beyond our own planet and how we can
leverage the mind boggling wealth that we have in our solar
system.  We have outgrown the carrying capacity of our
fragile pale blue dot and we need to start tapping
extraterrestrial resources or perish, certainly as a
civilization and eventually as a species.

The pattern language is organized around Steward Brand's
six-layer /Pace Layer/ model which is based on the
observation that different things change at different
speeds.  The model began as an observation that buildings
can be thought of as being made of multiple layers with each
changing over time at different speeds.

Brand's model was made up of six parts:

  - 6 Fashion
  - 5 Commerce
  - 4 Infrastructure
  - 3 Governance
  - 2 Culture
  - 1 Nature 


Our language will be called /A Pace-Layer Pattern Language/
(APPL), which will be made up of 9 parts that combine
Brand's and Saffo's Pace Layer models into one.

This view shows as slow to fast as pace layers, but it
should be remembered that layers 1-4 are nested within each
other and the Anthros layers are a subgroup of bios.

  |----------+------------------|
  |          | 9 Fashion        |
  |          | 8 Commerce       |
  | Anthros* | 7 Infrastructure |
  |          | 6 Governance     |
  |          | 5 Culture        |
  |----------+------------------|
  |          | 4 Anthros*       |
  |          | 3 Bios           |
  | Natura   | 2 Lithos         |
  |          | 1 Helios         |
  |          | 0 Cosmos         |
  |----------+------------------|


This is only one POV, we need to present this as how these
different things form a hierarchy so that it's understood
that anthros is a subset of bios and not seperate.

The 9th group called /0 Meta/ contains patterns that apply to
all layers which will be given the number 0 below /1 cosmos/
which is number 1.

Each layer has a different =Rate of Change= (ROC) with
/Cosmos/ at the bottom being the slowest and /Fashion/ at
the top in a constant state of churn, changing at a staccato
rapid-fire beat.


*** Pattern Keys

Patterns will have keys (unique ids) in the form of:

   APPL[layer#]:[Pattern#]

So the first pattern in the Meta group would have the key
APPL0:0001.

*** Steward Brand and Paul Saffo: Pace Layers Thinking -- notes

 - [[http://longnow.org/seminars/02015/jan/27/pace-layers-thinking/][Pace Layers Thinking]] | Stewart Brand & Paul Saffo | SALT
 - [[Painted.Woman.2017][Pace Layering: How Complex Systems Learn and Keep Learning]]

  slippage between layers, negative feedback looks

    - turbulence
    - viscosity

  young are concerned with fast layers -- especially fashion


  | Fast layers              | Slow layers          |
  |--------------------------+----------------------|
  | learns                   | remembers            |
  | proposes                 | disposes             |
  | absorbs shocks           | integrates shocks    |
  | discontinious            | continious           |
  | innovation/revolution    | constrainy/constancy |
  | *gets all the attention* | *has all the power*  |
 
I find it interesting that Alexander seems to be aware of
all of this, but never takes it on directly.  He has always
been focused on creating new buildings where you can start
with a clean slate and do things the right way.  But most of
the time that's not what you can do.  He always talks of
gradually moving from what is existing to how you want
things to be but doesn't address any of that in APL as much
as he could have.  We build on top of what came before.
There is no clean slate -- thinking that you can is the
architect's hubris.

The moments when you can do tabla rosa are few and far
between.  The great fire of london, a tsunami in Japan or SE
Asia wipe everything out, even cadastral maps (because the
property holders are gone as well as the buildings).  We
should fear such opportunities more than wish for them,
because unless you start small and grow bottom up in an
organic manner we will /always/ fuck it up.

But it's even worse than that because when say Myanmar or
Dubai backed by a mountain of cash have tried to clean slate
things they try to jump over all of the intermediate steps
that leads to functional, beautiful human settlements.

Alexander has essentially made the case to abolish the whole
class of architects and architecture as we know it today and
go back to the older concept of the master builder.

The big name architects are too focused on originality and
have largely forgotten craft and that structures are a part
of the environment (context) that they are built in and are
built for mostly pedestrian functions.  They put the focus
of vision on originality rather than achieving the purpose
the building is meant to fill.  The small name architects
are often just as bad or worse because they are just
knocking out structures at a distence according to
specifications provided by a customer that are based on
lowest common demoninator metrics and contruction financing
and practices that are estranged from the purpose that the
building is meant to fulfill.


**** Paul Saffo's Pace Layers

 - Anthros
 - Bios
 - Lithos
 - Cosmos

So if we combine this with Brand's model we get:

A General Theory Of Bureaucracy (1961)
Elliott Jaques

https://en.wikipedia.org/wiki/Elliott_Jaques

/Time span of discretion/ that a manager can be ranked 

seven layers on timespan of 

time from formulate a plan to it's execute

the lower the number the shorter the timespan



**** Japanese mayor (story from audience member)

An classic example of long term application of /timespan of
discretion/.

http://www.dailymail.co.uk/news/article-1386978/The-Japanese-mayor-laughed-building-huge-sea-wall--village-left-untouched-tsunami.html
http://blog.nihongo-pro.com/2011/04/mayors-vision-saves-japanese-village.html

Was mayor for over 40 years and in that time went against and fought
to build a tsunami barrier for this town.  He died before it was ever
used but the barrier saved the town.

**** Rice on Chessboard

People don't grok exponential growth

pace layers turn Hockey Sticks into S-Curves

**** The Apsara of Context, Scale, Time and Change

Though not discussed in the talk, the other two things that
we can't grok are /size/ and /time/ at scales that are
outside of human empirical limits.

Taken together /rate-of-change/ (ROC), /level-detail/ (LOC)
and /point-of-view/ (POV) are the three things that define
the context of almost anything.  They are also are our
biggest blindspots when any of the three fall outside of
human scales and comprehension.

Is blindspot the right term?  Failure of imagination?
Cognitive limitation?  hmmm.

Relativity is based on the concept that what is real is
dependent on the context of the observer -- this is just
another formulation of that concept from a different POV.

One of the Meta goals of our project is to find ways to help
us as individuals and collectively to make these things
comprehensible so that we act on them when it is necessary.

Climate Change is a problem because we can not comprehend
the problem that we have created for ourselves.  The Long
Now Foundation focuses on long term thinking and
perspectives but scale and change are equally important.  I
know that they think that's baked into their mission but its
worth spelling out.

*** Nature

We divide nature into the /1 cosmos/, /2 lithos/ (as in the
lithosphere) and /3 bios/ as in the biosphere.

Cosmos includes everything in the universe down to planetary
or planetoid scales.

Lithos (meaning rock) is any planet or planetoid where
mankind might end up hanging his hat or exploiting in some
manner.  Lithos includes artificial planetoids that are
meant to be habitats including everything from the ISS to
large scale habitats housing thousands or even millions of
people.

Bios is any biosphere that supports life that is contained
in a /lithos/.

Putting it all together:

The Universe is the Cosmos.  But more practically, the
pattern language will be concerned with our Solar System as
a /system/ which includes the Sun, planets, planetoids
orbiting it and the mechanics of moving around in it and
dealing with things like solar and cosmic radiation, light,
heat and electromagnetism and how all of this pertains to
building and maintaining an life and specifically an
antifragile distributed civilization.

The lithos is any physical inanimate natural or manmade body
that is exploited or used to create a habitat irrespective
of whether the body is habitable.

On earth the core, mantel and crust would be the lithosphere
and the biosphere is the thin envelop made up of an
atmosphere and a hydrosphere where life can exist.

The structure and shell of the ISS would be the lithos and
the atmosphere within and the machinery for maintaining
pressure, temperature and scrubbing C0^2 would be its
biosphere.

/Anthros/ layers are anything within a biosphere and follows
Steward Brand's five layers, culture, governance,
infrastructure, commerce and fashion.  There is always a
tradeoff when you define models like this because you are
indicating organization for the purpose of understanding
something that doesn't exist.  The layers are a useful way
of understanding how different aspects of civilization that
change at different speeds interact with each other.



----

We are a part of both realms and we impact and are impacted
by both realms.  We are part of nature, there is no them and
us.  This is very difficult concept for modern man to
comprehend because we have convinced ourselves that we are
exceptional and outside of nature.  Gravity applies to us
the same way as every other thing in the universe.  Jump out
of a airplane without something to slow us down like a
parachute and we will splat just like a watermelon.

A city is part of nature as much as the most isolated meadow
in on the Tibetan Plateau.  Both belong to and depend on the
same pressurized atmosphere, and protection from solar and
cosmic radiation to support life.  You can say that the
meadow is nature uneffected by man, but that isn't exactly
true either.  Mankind has been shaping the world for tens of
thousands of years using fire, long before the first
civlizations emerged in the alluvial wetlands of Mesopotamia
that fundementally changed the biodiversity of broad swaths
of the planet, especially megafuana.  Cliff paintings
overlooking the Mekong River portray a number of different
types of megafauna that are now long extinct.  The most
likely explanation for the extinction of species like pygmy
rhinos and the giant sloth is man.  Other megafauna, which
could reproduce quickly and were more fleet of foot than the
sloth such as antelope, deer, caribou and elk flourished as
a reliable food source managed by using fire to shape
habitats which encouraged those species.  It can be argued
that mankind terraformed the planet with fire.

/Nature/ patterns are concerned with Mankind's interaction
with nature, both physical and living.

The degree of that interaction can be divided into wild and
cultivated.  We used to be quite good at managing the wild,
but got lost when we turned to pure cultivation and
eventually began to see the wild as something in opposition
to and an enemy of the cultivated.  In modern times, those
who call themselves environmentalists and conservationists
are no less guilty of this false dichotomy.  We need to stop
thinking in terms of us vs them, nature knows no such
divisions.  We can not become one with nature, because we
were never apart from nature in the first place.

When talking about the realm of life we will use the concept
of /habitats/ that contain /biospheres/ that are sometimes
divided into /biomes/ that contain life.  At the time that
this is being written there are only two biospheres that we
are aware of, the planetary biosphere that envelops Earth
and a tiny biosphere in low earth orbit called the ISS
(International Space Station).  Eventually there will be
more biospheres, a handful at planetary scales and many
smaller artificial ones.  The nature of how mankind shapes
and manages those biospheres is the subject of this pattern
pace-layer.

Change at planetary scales both physical and biological take
place in geological time scales.  The tectonic plates of the
Earth inch together and apart so slowly even the Ents would
consider them to be slow.  The evolution of life largely
takes place in time scales that dwarf any one species.
Occasionally something like an asteroid impact, the eruption
of a supervolcano or other event triggers massive change,
but the impact of that event often takes far longer than we
might think.  The dinosaurs didn't all die off within days
or months or even centuries after the asteroid hit the
Yuccatan.  A true planet killing event has yet to happen to
Earth.  We know this because we are here to talk about it.
But there were a couple of times that things were close.



** Primer

  - origin
  - theses
  - education
  - shops & guilds
  - value-chain
  - 
  - bioregions/ecosystems
  - production & surpluses

*** Origin Story
  - [[./manifesto-filters.org][Filters]]

  - 1. The Big Bang
  - 2. Stars Light Up
  - 3. New Chemical Elements
  - 4. Earth and the Solar System

  - [[./manifesto-life.org][Life]]
  - 5. Life on Earth
  - 6. Collective Learning
  - 7. Agricuture
  - 8. The Modern Revolution

  - [[./manifesto-savannah.org][Savannah]]
  - [[./manifesto-cognition.org][Cognition]]
  - [[./manifesto-polis.org][Polis]]
  - [[./manifesto-fragility.org][Fragility]]
  - [[./manifesto-estrangement.org][Estrangement]]
  - [[./manifesto-social.org][Social]]
  - [[./manifesto-natures.org][Natures]]
  - [[./manifesto-storms.org][Storms]]
  - [[./manifesto-maps.org][Maps]]
  - [[./manifesto-stories.org][Stories]]


** Hoard
*** Constants

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

 - [[./constant-speed-of-light.org][Speed of Light]]
 - [[./constant-dunbar.org][Dunbar's Number]]
 - [[./constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./constant--shared_intentionality.org][Shared Intentionality]]

*** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./theses-preamble.org][Preamble]]
 - [[./theses-notes.org][Theses Notes]]



** Arc

** Roadmap

A Roadmap for Mankind over the next 50 years to move from
being a centralized global civilization, with crtical
knowledge, infrastructure and wealth pooled in a handful of
people, places, and organizations, to a distributed
multiplanetary civilization reflecting the needs of a
rapidly shrinking population on earth and an increasingly
hostile climate.

 - [[./roadmap-overview.org][Overview]] 

