#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Manifesto | TOC

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Manifesto | Table of Contents
:PROPERTIES:
:CUSTOM_ID:
:Name:      /home/deerpig/proj/chenla/manifesto/index.org
:Created:   2017-10-06T18:08@Prek Leap (11.642600N-104.919210W)
:ID:        730bbfc9-e0cb-4c6f-97e0-4dbdef81b4d9
:VER:       560560166.539684901
:GEO:       48P-491193-1287029-15
:BXID:      proj:TWT0-8431
:Class:     primer
:Entity:    toc
:Status:    wip 
:Licence:   MIT/CC BY-SA 4.0
:END:

** The Warp and Woof: A Scopic Prologomenon

#+begin_quote
1. warp and woof(Noun)

   The threads in a woven fabric, comprised of the warp
   (threads running lengthwise) and woof (threads running
   crosswise) to create the texture of the fabric.

2. warp and woof(Noun)

   The fundamental structure of any process or system.

-- [[http://www.definitions.net/definition/warp%20and%20woof][warp and woof]] | definitions.net
-- [[https://en.wiktionary.org/wiki/warp_and_woof][warp and woof]] | Wiktionary
#+end_quote


  - [[./manifesto-filters.org][Filters]]

  - 1. The Big Bang
  - 2. Stars Light Up
  - 3. New Chemical Elements
  - 4. Earth and the Solar System

  - [[./manifesto-life.org][Life]]
  - 5. Life on Earth
  - 6. Collective Learning
  - 7. Agricuture
  - 8. The Modern Revolution



  - [[./manifesto-savannah.org][Savannah]]
  - [[./manifesto-cognition.org][Cognition]]
  - [[./manifesto-polis.org][Polis]]
  - [[./manifesto-fragility.org][Fragility]]
  - [[./manifesto-estrangement.org][Estrangement]]
  - [[./manifesto-social.org][Social]]
  - [[./manifesto-natures.org][Natures]]
  - [[./manifesto-storms.org][Storms]]
  - [[./manifesto-maps.org][Maps]]
  - [[./manifesto-stories.org][Stories]]
  - [[./manifesto-window.org][Window]]

** The Yellow Brick Road: a manifesto for an augmented distributed civilization

The manifesto should map out the augmented distributed
civilization we propose to build that will act like a 
soap bubble overlaying the existing civilization.

  - [[./manifesto-yellow.org][The Yellow Brick Road]]

** Patterns

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.

APL was divided into three parts, Towns, Buildings and
Construction.  But APL is a pattern language for
architecture and buildings.  For this to work it had to
define many patterns that more properly belonged to urban
planning, culture and governance though these were patterns
that supported the construction of beautiful buildings.

Our pattern language has a far broader scope; building an
antifragile civilization for mankind.  It is such a broad,
and ambitious scope that it borders on hubris.  After all we
barely agree on what civilization is, let alone how to build
one from first principles.  Though the undertaking is
assuredly fated to fall far short of it's goals, it is
important to instigate a tradition of people and
institutions to try.  Over many generations such
investigations could well become the foundation for and
roadmap for our survival and hopefully, prosperity.

But if Mankind is to become antifragile, we must become as
distributed as possible.  That means, among other things we
need to be thinking beyond our own planet and how we can
leverage the mind boggling wealth that we have in our solar
system.  We have outgrown the carrying capacity of our
fragile pale blue dot and we need to start tapping
extraterrestrial resources or perish, certainly as a
civilization and eventually as a species.

The pattern language is organized around Steward Brand's
six-layer /Pace Layer/ model which is based on the
observation that different things change at different
speeds.  The model began as an observation that buildings
can be thought of as being made of multiple layers with each
changing over time at different speeds.

Brand's model was made up of six parts:

  - 6 Fashion
  - 5 Commerce
  - 4 Infrastructure
  - 3 Governance
  - 2 Culture
  - 1 Nature 


Our language will be called /A Pace-Layer Pattern Language/
(APPL), which will be made up of 9 parts that combine
Brand's and Saffo's Pace Layer models into one.

  |---------+------------------+------|
  |         | 8 Fashion        |      |
  |         | 7 Commerce       | Fast |
  | Anthros | 6 Infrastructure |      |
  |         | 5 Governance     |      |
  |         | 4 Culture        |      |
  |---------+------------------+------|
  |         | 3 Bios           |      |
  | Natura  | 2 Lithos         | Slow |
  |         | 1 Cosmos         |      |
  |---------+------------------+------|
  | Meta    | 0                |      |


The 9th group called /Meta/ contains patterns that apply to
all layers which will be given the number 0 below /cosmos/
which is number 1.

Each layer has a different =Rate of Change= (ROC) with
/Cosmos/ at the bottom being the slowest and /Fashion/ at
the top in a constant state of churn, changing at a staccato
rapid-fire beat.

Patterns will have keys (unique ids) in the form of:

   APPL[layer#]:[Pattern#]

So the first pattern in the Meta group would have the key
APPL0:0001.

**** Steward Brand and Paul Saffo: Pace Layers Thinking -- notes

 - http://longnow.org/seminars/02015/jan/27/pace-layers-thinking/

  slippage between layers, negative feedback looks

    - turbulence
    - viscosity

  young are concerned with fast layers -- especially fashion


  | Fast layers              | Slow layers          |
  |--------------------------+----------------------|
  | learns                   | remembers            |
  | proposes                 | disposes             |
  | absorbs shocks           | integrates shocks    |
  | discontinious            | continious           |
  | innovation/revolution    | constrainy/constancy |
  | *gets all the attention* | *has all the power*  |
 
**** Paul Saffo's Pace Layers

 - Anthros
 - Bios
 - Lithos
 - Cosmos

So if we combine this with Brand's model we get:

A General Theory Of Bureaucracy (1961)
Elliott Jaques

https://en.wikipedia.org/wiki/Elliott_Jaques

/Time span of discretion/ that a manager can be ranked 

seven layers on timespan of 

time from formulate a plan to it's execute

the lower the number the shorter the timespan



**** Japanese mayor (story from audience member)

An classic example of long term application of /timespan of
discretion/.

http://www.dailymail.co.uk/news/article-1386978/The-Japanese-mayor-laughed-building-huge-sea-wall--village-left-untouched-tsunami.html
http://blog.nihongo-pro.com/2011/04/mayors-vision-saves-japanese-village.html

Was mayor for over 40 years and in that time went against and fought
to build a tsunami barrier for this town.  He died before it was ever
used but the barrier saved the town.

**** Rice on Chessboard

People don't grok exponential growth

pace layers turn Hockey Sticks into S-Curves

**** The Apsara of Context, Scale, Time and Change

Though not discussed in the talk, the other two things that
we can't grok are /size/ and /time/ at scales that are
outside of human empirical limits.

Taken together /rate-of-change/ (ROC), /level-detail/ (LOC)
and /point-of-view/ (POV) are the three things that define
the context of almost anything.  They are also are our
biggest blindspots when any of the three fall outside of
human scales and comprehension.

One of the Meta goals of our project is to find ways to help
us as individuals and collectively to make these things
comprehensible so that we act on them when it is necessary.

Climate Change is a problem because we can not comprehend
the problem that we have created for ourselves.  The Long
Now Foundation focuses on long term thinking and
perspectives but scale and change are equally important.

*** Nature

We divide nature into the /1 cosmos/, /2 lithos/ (as in the
lithosphere) and /3 bios/ as in the biosphere.

Cosmos includes everything in the universe down to planetary
or planetoid scales.

Lithos (meaning rock) is any planet or planetoid where
mankind might end up hanging his hat or exploiting in some
manner.  Lithos includes artificial planetoids that are
meant to be habitats including everything from the ISS to
large scale habitats housing thousands or even millions of
people.

Bios is any biosphere that supports life that is contained
in a /lithos/.

Putting it all together:

The Universe is the Cosmos.  But more practically, the
pattern language will be concerned with our Solar System as
a /system/ which includes the Sun, planets, planetoids
orbiting it and the mechanics of moving around in it and
dealing with things like solar and cosmic radiation, light,
heat and electromagnetism and how all of this pertains to
building and maintaining an life and specifically an
antifragile distributed civilization.

The lithos is any physical inanimate natural or manmade body
that is exploited or used to create a habitat irrespective
of whether the body is habitable.

On earth the core, mantel and crust would be the lithosphere
and the biosphere is the thin envelop made up of an
atmosphere and a hydrosphere where life can exist.

The structure and shell of the ISS would be the lithos and
the atmosphere within and the machinery for maintaining
pressure, temperature and scrubbing C0^2 would be its
biosphere.

/Anthros/ layers are anything within a biosphere and follows
Steward Brand's five layers, culture, governance,
infrastructure, commerce and fashion.  There is always a
tradeoff when you define models like this because you are
indicating organization for the purpose of understanding
something that doesn't exist.  The layers are a useful way
of understanding how different aspects of civilization that
change at different speeds interact with each other.



----

We are a part of both realms and we impact and are impacted
by both realms.  We are part of nature, there is no them and
us.  This is very difficult concept for modern man to
comprehend because we have convinced ourselves that we are
exceptional and outside of nature.  Gravity applies to us
the same way as every other thing in the universe.  Jump out
of a airplane without something to slow us down like a
parachute and we will splat just like a watermelon.

A city is part of nature as much as the most isolated meadow
in on the Tibetan Plateau.  Both belong to and depend on the
same pressurized atmosphere, and protection from solar and
cosmic radiation to support life.  You can say that the
meadow is nature uneffected by man, but that isn't exactly
true either.  Mankind has been shaping the world for tens of
thousands of years using fire, long before the first
civlizations emerged in the alluvial wetlands of Mesopotamia
that fundementally changed the biodiversity of broad swaths
of the planet, especially megafuana.  Cliff paintings
overlooking the Mekong River portray a number of different
types of megafauna that are now long extinct.  The most
likely explanation for the extinction of species like pygmy
rhinos and the giant sloth is man.  Other megafauna, which
could reproduce quickly and were more fleet of foot than the
sloth such as antelope, deer, caribou and elk flourished as
a reliable food source managed by using fire to shape
habitats which encouraged those species.  It can be argued
that mankind terraformed the planet with fire.

/Nature/ patterns are concerned with Mankind's interaction
with nature, both physical and living.

The degree of that interaction can be divided into wild and
cultivated.  We used to be quite good at managing the wild,
but got lost when we turned to pure cultivation and
eventually began to see the wild as something in opposition
to and an enemy of the cultivated.  In modern times, those
who call themselves environmentalists and conservationists
are no less guilty of this false dichotomy.  We need to stop
thinking in terms of us vs them, nature knows no such
divisions.  We can not become one with nature, because we
were never apart from nature in the first place.

When talking about the realm of life we will use the concept
of /habitats/ that contain /biospheres/ that are sometimes
divided into /biomes/ that contain life.  At the time that
this is being written there are only two biospheres that we
are aware of, the planetary biosphere that envelops Earth
and a tiny biosphere in low earth orbit called the ISS
(International Space Station).  Eventually there will be
more biospheres, a handful at planetary scales and many
smaller artificial ones.  The nature of how mankind shapes
and manages those biospheres is the subject of this pattern
pace-layer.

Change at planetary scales both physical and biological take
place in geological time scales.  The tectonic plates of the
Earth inch together and apart so slowly even the Ents would
consider them to be slow.  The evolution of life largely
takes place in time scales that dwarf any one species.
Occasionally something like an asteroid impact, the eruption
of a supervolcano or other event triggers massive change,
but the impact of that event often takes far longer than we
might think.  The dinosaurs didn't all die off within days
or months or even centuries after the asteroid hit the
Yuccatan.  A true planet killing event has yet to happen to
Earth.  We know this because we are here to talk about it.
But there were a couple of times that things were close.



** Constants

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

 - [[./constant-speed-of-light.org][Speed of Light]]
 - [[./constant-dunbar.org][Dunbar's Number]]
 - [[./constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./constant--shared_intentionality.org][Shared Intentionality]]


** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./theses-preamble.org][Preamble]]
 - [[./theses-notes.org][Theses Notes]]


** Roadmap

A Roadmap for Mankind over the next 50 years to move from
being a centralized global civilization, with crtical
knowledge, infrastructure and wealth pooled in a handful of
people, places, and organizations, to a distributed
multiplanetary civilization reflecting the needs of a
rapidly shrinking population on earth and an increasingly
hostile climate.

 - [[./roadmap-overview.org][Overview]] 

