#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Manifesto | TOC
:PROPERTIES:
:CUSTOM_ID:
:Name:      /home/deerpig/proj/chenla/manifesto/index.org
:Created:   2017-10-06T18:08@Prek Leap (11.642600N-104.919210W)
:ID:        730bbfc9-e0cb-4c6f-97e0-4dbdef81b4d9
:VER:       560560166.539684901
:GEO:       48P-491193-1287029-15
:BXID:      proj:TWT0-8431
:Class:     primer
:Entity:    toc
:Status:    wip 
:Licence:   MIT/CC BY-SA 4.0
:END:

* Manifesto | Table of Contents
[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Manifesto

  - [[./manifesto-yellow.org][The Yellow Brick Road]]
  - [[./manifesto-filters.org][Filters]]
  - [[./manifesto-savannah.org][Savannah]]
  - [[./manifesto-cognition.org][Cognition]]
  - [[./manifesto-fragility.org][Fragility]]
  - [[./manifesto-estrangement.org][Estrangement]]
  - [[./manifesto-social.org][Social]]
  - [[./manifesto-natures.org][Natures]]
  - [[./manifesto-storms.org][Storms]]
  - [[./manifesto-maps.org][Maps]]
  - [[./manifesto-stories.org][Stories]]
  - [[./manifesto-window.org][Window]]

* Constants

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

 - speed of light
 - [[./constant-dunbar.org][Dunbar's Number]]


* Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.


 - [[./theses-preamble.org][Preamble]]

Nature makes no declarations. There is only the inevitable
interactions of matter, energy, space and time as determined
first, by the imutable Laws established in the ensuing chaos
of the Big Bang, and second, in slow counterpoint, the mills
of entropy, grinding and unwinding it all until there is
nothing but eternal cold and darkness.  As far as we know,
the only force working against entropy is Life.  Chance
dictates the direction and directives that Life follows out
of necessity.  We are an evolutionary experiment that has
been given the power to replace the dice that dictate the
direction Life takes.

We make no claim to divine, natural or moral authority,
other than being sentient beings, with some measure of free
will, that depend on each other for survival and well being.
No where has this been articulated with such humility,
beauty and grace as Charles Darwin did in May of 1860 in a
letter to Ada Gray:

#+begin_quote
I cannot see, as plainly as others do, & as I sh^d wish to
do, evidence of design & beneficence on all sides of
us. There seems to me too much misery in the world. I cannot
persuade myself that a beneficent & omnipotent God would
have designedly created the Ichneumonidæ with the express
intention of their feeding within the living bodies of
caterpillars, or that a cat should play with mice. Not
believing this, I see no necessity in the belief that the
eye was expressly designed. On the other hand I cannot
anyhow be contented to view this wonderful universe &
especially the nature of man, & to conclude that everything
is the result of brute force. I am inclined to look at
everything as resulting from designed laws, with the
details, whether good or bad, left to the working out of
what we may call chance. Not that this notion at all
satisfies me. I feel most deeply that the whole subject is
too profound for the human intellect. A dog might as well
speculate on the mind of Newton.— Let each man hope &
believe what he can.—

-- [[http://www.darwinproject.ac.uk/letter/DCP-LETT-2814.xml][Charles Darwin, Letter to Asa Gray]] 22 May [1860]
#+end_quote

For this reason we give these assertions the name /theses/
and not /rights/ as claimed in the United States Bill of
Rights, the English Bill of Rights, the Magna Carta and more
recently, the United Nations Bill of Universal Rights.

Though there is no claim that these theses are anything more
than being the best that mankind can hope for, believe in,
and aspire to, we do assert that such humble authority is as
inalienable as any that mankind has ever laid claim to.  To
abandon such principles as not being fundamental and
incontrovertible would undermine and abandon the
underpinings of our very humanity and place in mortal
jeopardy our ability to cooperate and maintain any semblance
of civilization apon which our survival as individuals and
as a species depends.





 - [[./theses-notes.org][Theses Notes]]


* Patterns

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.
