#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall
#+TITLE:   Manifesto | TOC

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Manifesto | Table of Contents
:PROPERTIES:
:CUSTOM_ID:
:Name:      /home/deerpig/proj/chenla/manifesto/index.org
:Created:   2017-10-06T18:08@Prek Leap (11.642600N-104.919210W)
:ID:        730bbfc9-e0cb-4c6f-97e0-4dbdef81b4d9
:VER:       560560166.539684901
:GEO:       48P-491193-1287029-15
:BXID:      proj:TWT0-8431
:Class:     primer
:Entity:    toc
:Status:    wip 
:Licence:   MIT/CC BY-SA 4.0
:END:

** The Warp and Woof: A Scopic Prologomenon

#+begin_quote
1. warp and woof(Noun)

   The threads in a woven fabric, comprised of the warp
   (threads running lengthwise) and woof (threads running
   crosswise) to create a the texture of the fabric.

2. warp and woof(Noun)

   The fundamental structure of any process or system.

-- [[http://www.definitions.net/definition/warp%20and%20woof][warp and woof]] | definitions.net
-- [[https://en.wiktionary.org/wiki/warp_and_woof][warp and woof]] | Wiktionary
#+end_quote


  - [[./manifesto-filters.org][Filters]]

  - 1. The Big Bang
  - 2. Stars Light Up
  - 3. New Chemical Elements
  - 4. Earth and the Solar System

  - [[./manifesto-life.org][Life]]
  - 5. Life on Earth
  - 6. Collective Learning
  - 7. Agricuture
  - 8. The Modern Revolution



  - [[./manifesto-savannah.org][Savannah]]
  - [[./manifesto-cognition.org][Cognition]]
  - [[./manifesto-polis.org][Polis]]
  - [[./manifesto-fragility.org][Fragility]]
  - [[./manifesto-estrangement.org][Estrangement]]
  - [[./manifesto-social.org][Social]]
  - [[./manifesto-natures.org][Natures]]
  - [[./manifesto-storms.org][Storms]]
  - [[./manifesto-maps.org][Maps]]
  - [[./manifesto-stories.org][Stories]]
  - [[./manifesto-window.org][Window]]

** The Yellow Brick Road: a manifesto for an augmented distributed civilization

The manifesto should map out the augmented distributed
civilization we propose to build that will act like a 
soap bubble overlaying the existing civilization.

  - [[./manifesto-yellow.org][The Yellow Brick Road]]

** Patterns

Patterns are repeating themes in nature, design and human
behavior that when combined with other patterns strengthen
each other and create things that are larger than the sum of
their parts.

APL was divided into three parts, Towns, Buildings and
Construction.  But APL is a pattern language for
architecture and buildings.  For this to work it had to
define many patterns that more properly belonged to urban
planning, culture and governance though these were patterns
that supported the construction of beautiful buildings.

Our pattern language has a far broader scope; building an
antifragile civilization for mankind.  It is such a broad,
ambitious scope that it borders on hubris.  After all we
barely agree on what civilization is, let alone how to build
one from first principles.

But if Mankind is to become antifragile, we must become as
distributed as possible.  That means, among other things we
need to be thinking beyond our own planet and how we can
leverage the mind boggling wealth that we have in our solar
system.  We have outgrown the carrying capacity of our
fragile pale blue dot and we need to start tapping
extraterrestrial resources or perish, certainly as a
civilization and eventually as a species.

The pattern language is organized around Steward Brand's
six-layer /Pace Layer/ model which is based on the
observation that different things change at different speeds.

** Constants

Constants are bedrock variables that define things that can
not be changed like the speed of light or dunbar's number.
They supercede what we want or what we would like and
provide empirical design limits.  No theses can =violate= or
contradict a =constant=.

 - [[./constant-speed-of-light.org][Speed of Light]]
 - [[./constant-dunbar.org][Dunbar's Number]]
 - [[./constant-millers-law.org][Miller's Law]] (7 plus or minus 2)
 - [[./constant-divided-concurrent-goals.org][Divided Concurrent Goals]]
 - [[./constant--shared_intentionality.org][Shared Intentionality]]


** Theses

Scopic Theses are declarations that provide a foundation for
a =civil ruleset= for people to live and cooperate with each
other.  Our theses is a social fiction that defines how we
/want/ to live and behave with each other.

 - [[./theses-preamble.org][Preamble]]
 - [[./theses-notes.org][Theses Notes]]


** Roadmap

A Roadmap for Mankind over the next 50 years to move from
being a centralized global civilization, with crtical
knowledge, infrastructure and wealth pooled in a handful of
people, places, and organizations, to a distributed
multiplanetary civilization reflecting the needs of a
rapidly shrinking population on earth and an increasingly
hostile climate.

 - [[./roadmap-overview.org][Overview]] 

