#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Filters
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-filters.org
:Created:   2017-10-17T19:03@Prek Leap (11.642600N-104.919210W)
:ID:        fb21fc98-959b-4830-ac18-ea28d0a83db1
:VER:       561513899.774837850
:GEO:       48P-491193-1287029-15
:BXID:      proj:WTY3-1200
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

We start by talking about entropy and information 

-- then move on to complexity which is what makes the
universe we live in and our existence possible.


This section will talk about several different sets of
filters.  The Big History folks call these /thresholds/, but
we'll continue to frame it in terms of the [[https://en.wikipedia.org/wiki/Fermi_paradox][Fermi paradox]],
and Drake's Equation but expand the concept to the entire
universe.

  - [[http://www.osti.gov/accomplishments/documents/fullText/ACC0055.pdf]["Where is everybody?" An account of Fermi's question]] |
     Eric Jones (1985) Los Alamos National Laboratory
     OSTI ID 785733

The other thing we will do is frame the evolution of the
universe as Drake's Equation -- which includes variables for
star formation and fraction of stars that have planets, and
planets in the goldilocks zone.

We can then expand on Drake to include the preconditions for
the physical universe that are needed to support carbon
based life on earth.

We can do this, because the universe is, by definition,
anthropic becuase the natural laws that emerged from the
initial conditions of the big bang make life possible.
Change those initial conditions slightly and you get a
universe that can not support the kind of complexity that
results in life.

We can use multiple sets of filters.

  - Cosmic Filters :: that resulted in galaxies, with stars
                      that produce a wide variety of
                      elements and support small rocky
                      planets in a goldilocks zone.

  - Life Filters   :: Life on Earth has gone through a
                      number of filters as well that have
                      determined how life has evolved. These
                      have been governed by extinction
                      events from Climate change triggered
                      by asteroid impacts and in at least
                      one case, the extinction of CO2 based
                      life which produced so much waste
                      oxygen that it eventually destroyed
                      everything.

   - Anthropic     :: The evolution of man, as a species and
                      eventually as a civilization. 

I prefer to use multiple sets of filters instead of one huge
one for the simple reason that conflating human filters that
happen at cosmic scales, or even planetary scales is not
terribly humble -- if for no other reason than we don't know
how common life is in the universe.  If it's common, then
it's uncertain what complexity filters would be true
collectively for life.  And the same goes for anthropic
filters.  When talking about this we should explain that
unless we have evidence to the contrary we should assume
that the [[https://en.wikipedia.org/wiki/Mediocrity_principle][mediocrity principle]] holds true..

The other reason to maintain different sets is that many
anthropic filters overlap with life filters.


Each filter requires goldilocks conditions in order to go to
the next step.  Without these conditions, things would have
been stuck at a certain level, or resulted in collapse or
destruction.   This is why we use the term /filter/ instead
of /threshold/.





----

start with life arising after the earth cools -- it could
have arisen here, or elsewhere and piggybacked on a comet or
meteriod -- it's possible it might even be from another
star, riding on a piece of rock ejected from another planet
on another star at some distant time in the past when our
star brushed up against our neightbor's Oort cloud and
exchanged debris -- caught in our Oort Cloud for millennia
before some random event pulled it in towards the sun but
impacted earth first.  we will only know if we ever visit
the stars and find life there that is us... In any event,
somehow, some xxx years ago life began.

filters for life on earth have come in the form of five
great events that resulted in catastrophic climate change
where 75-96% of species on the planet were wiped out

 - End Ordovician, 444 mya, 86% of species lost 
 - Late Devonian, 375 mya, 75% of species lost
 - End Permian, 251 mya, 96% of species lost
 - End Triassic, 200 mya, 80% of species lost
 - End Cretaceous, 66 mya, 76% of all species lost

life is tenacious and antifragile, once it takes hold, it's
astonishing how much punishment it can take and eventually
rebound, stronger and more complex than ever.

the extinction events have acted like the black plague that
wiped out xxx% of the world's population, or the great fire
of london -- it cleaned things out and reset the clock
setting the stage for an evolutionary explosion of new life
racing to fill in all of the ecological niches that had been
left vacant. without the past four extinction events life on
earth may well only be marginally different from how it was
in the Ordovician.  Life has a tendency to reach
equilibriums that can last a very very long time.

the patterns are very clear, and they scale -- climate
change, carrying capacity of an ecosystem, carrying capacity
of a biosphere -- impact the climate and you change the
carrying capacity -- when this happens to an ecosystem in a
biome species go extinct.  when this happens to the
biosphere, you get mass extinction events.

mankind has moved from the small stage of impacting and
being impacted by specific biomes, to being a major player
effecting the entire biosphere.  and we're now doing this in
timescales that can be measured in 2-3 generations.  if that
doesn't blow your mind you weren't paying attention.  if it
did blow your mind and you aren't terrified then there is
something wrong with you.  and if we as a species aren't
terrified by this enough to change our behavior then we are
lost.


