#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Life
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Life
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-life.org
:Created:   2017-10-20T08:15@Prek Leap (11.642600N-104.919210W)
:ID:        563bceff-86c9-4e71-84c1-a68e4a949626
:VER:       561734171.446045487
:GEO:       48P-491193-1287029-15
:BXID:      proj:LQR3-4347
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:


** Introduction

All too often evolution is framed in terms of competition, of winners
and losers.  But perhaps evolution is better thought of as a story of
cooperation, multicellular life, complex organisms, complementing,
feeding and reinforcing each other to create a biosphere made up of
many interdependent ecosystems.  Man is a success story only because
of cooperation, of small bands of hunter gatherers, of villages and
cities, and the civilizations that weave them together.

The conceit of the individual is a culmulative illusion, a fiction
fabricated by our brain attempting to piece together a continious
model of the world around us while working around our physical and
cognitive limits.

We are the true children of Janus; holons made from countless parts,
that make a whole, even as that whole is in turn just a part of
something much larger than ourselves.  It's all turtles, all the way
down, and all the way up.  We're just a turtle in the middle.


---

So why this chapter/section?  Is it important to talk about
life and evolution?

We are part of life on this planet, and we'll have to bring
a hefty chunk of it with us wherever we go.

Life is all about DNA -- in fact, all life is, is a
mechanism for replicating DNA.  Dawkin's selfish gene etc.

Life builds on life, always becoming more complex, but also
more robust --  life is the ultimate antifragile system

DNA is all about leveraging chance/chaos to reinforce
itself, become more antifragile and more complex.  Sex is a
vital part of this because survival of life requires it to
be able to adapt, and the only way to adapt is to recombine
genetic material to increase the occurance of mutations that
benifit a species.  Without sex, evolution would probably
not work -- mutations would only be able to propagate
unevenly or not at all.  But if each replication was the
product of combining two sets of similar DNA then DNA will
change over successive generations and beneficial mutations
will propagate.

It's important that we understand ourselves relative to and
as part of Life and Earth's biosphere.

As a matter of survival, DNA will benifit by Life spreading
to other planets, and eventually to other stars.  There are
a few hit or miss mechanisms for this to happen, mostly by
piggybacking on rocks and ice that have been ejected from a
planet after a comet or asteroid strike.  Some of these
chunks of ice and rock might then end up eventually in the 
Oort cloud, and when the Sun moves close enough to another
star as it orbits the center of the galaxy, some of those
rocks and ice might be pulled into the other star's Oort
cloud and eventually land on a planet that could sustain
life.

But man is a far better means of exporting life.  If we
become a spacefaring species, we will agressively bring life
throughout the solar system and possibly to other stars.

