#   -*- mode: org; fill-column: 60 -*-

#+TITLE: From Domus to Polis | Manifesto
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-polis.org
:Created:   2017-10-28T10:38@Prek Leap (11.642600N-104.919210W)
:ID:        e23ed9f1-530b-4e8f-9cfa-e0045e3ed0d9
:VER:       562433977.494582515
:GEO:       48P-491193-1287029-15
:BXID:      proj:LOF3-8407
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]
[[https://www.patreon.com/chenla][https://img.shields.io/badge/Patreon-contribute-yellow.svg]]


  - we began on the savannah
  - we became sedantary in the marsh at the intersection
    between three food webs
  - we were then domesticated (the domus) by cereals and 
    vulnerable to crowding diseases - this took 5ky as the
    slight increase in birth rates tipped the balance.
  - the walls went up to keep us in as much as others out
    which was the beginning of the state
  - writing systems began as accounting, not speech, as a
    means of making people legible and collect taxes

  - all monocultures are bad -- human, agricultural, social


* Introduction


  - dependence on cerals is not sustainable -- need to mix
    both annuals and perenials
  - shared services must be automated and shared through a
    trustless infrastructure
  - land and natural resources are a shared commons -- not
    privately owned
  - no inheritence of wealth or property beyond personal
    items that have emotional, historic, symbolic value or
    are associated with a good story. equity in companies,
    and personal wealth in the form of money should pass to
    the covey they belong to at death, and become part of
    the covey's commons.
  - all monopolies indicate systemic failure
  - food, shelter, medical care, education, access to
    communiction, processing and storage are base human
    rights
  - markets must be free, but fair and designed to serve
    everyone's needs, not provide advantages for a few
  - markets also must be designed so that the automated
    infrastructure at the heart of everything is paid for --
    this will provide the same function that taxes do in
    today's states
  - ideologies and belief systems can not be imposed on
    others, and they can never be allowed to subvert or
    override any basic human rights -- including the ban on
    monocultures.
  - people will do bad things when it is easier to do the
    wrong thing than to do the right thing, and when they
    see an advantage or reward in doing the wrong thing.
  - enforcement keeps things free and fair, when someone
    does the wrong thing, it should be corrected, and the
    only criteria for taking away someone's freedom is if
    they pose a threat to others.  Punishment or vengence has
    no place in a civilized society and is not an act of
    justice.
  - explotation of prisoners is nothing less than a form of
    slavery.
  - incarceration does not forfeit a person's rights and
    participation in society except in specific
    circumstances where they would pose a threat to others.




----

I've never felt comfortable with the idea of urbanization -- there was
always something that smelt wrong about it.  A city is simply a human
monoculture.  Nothing good comes from monocultures of any type, so why
should human monocultures be a good thing?

There is a growing body of evidence that cities and states did not
arise as naturally as we've been told -- and that there was a great
deal of resistence to urban life.  It would seem that people were
forced to live in cities and states as captives, or slaves.  Life in
cities was and still isn't very nice.

There are a number of people I respect who wax poetic about cities and
urban life, including Steward Brand, but I've never bought into it.

The advantages of cities all comes down to communication and logistics
-- when people live close to each other they can coordinate and
cooperate in ways that a population spread over a large area can not
do.

This is no longer true -- the Internet will soon make these advantages
largely moot.  Not quite yet, but soon.  Once telepresence becomes the
norm it will be.  But it's still a lot more complicated than that.
The challenge is to build a distributed civilization that is
geographically spread out somewhat thinly, but still remain
cosmopolitan -- that means that though we are spread out, we can not
be completely sedantary -- we must be mobile so that we can live and
work and learn to commiunicate and cooperate with a wide variety of
different people.  Cities have traditionally done this.

----

The other problem is the whole concept of the state -- which provides
a number of functions that seem to be equally benificial and
repressive at the same time.

States create hierarchies that create power and wealth imbalances.
The larger those imbalances are, the worse off most people are.
States serve those at the top of hierarchies, and give those people
freedom, security, liberty and comfort -- but those at the bottom are
trapped, poor, often sick, and miserable.

At the base of all of this are cereal crops which are, as Scott points
out, both legible and taxable.  If you control the land, and control
the people on the land, cereals are the best way do to do both.

Egalitarian societies don't scale -- 

States and land ownership seem to the two of things holding us back
more than anything else.
