#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Natures
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-natures.org
:Created:   2017-10-17T19:11@Prek Leap (11.642600N-104.919210W)
:ID:        3661a1a7-0ed8-4098-8034-9ac8e53bf116
:VER:       561514369.221788091
:GEO:       48P-491193-1287029-15
:BXID:      proj:FCM5-6277
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]



The agricultural and industrial revolutions have trashed the
way that all members of Mankind live.  In an blink of an
eye, by evolutionary timescales, all of us, Sapiens and all
the creatures (both flora and fauna) we domesticated and
took along for the ride now live a very uneasy existence
that is out of sync with our natures.

It is not too much to ask that each of our natures be
respected and each us be allowed to live our lives, no
matter how short or long, in a manner that reflects our
natural instincts, strengths and weakneses.

Let's start with plants.  It might sound strange to advocate
that plants be allowed to live according to their natures.
It has nothing to do with attributing human traits to
plants.  It is much more about sound farming and ecological
management practicess.

We now grow a handful of spieces of plants in absolute
artificial monocultures.  We have separated individual
species, almost all of which are annuals, and separated them
from broad ecosystem populated by plants, insects, micro
organisms and animals and forced them to grow on their own.
There is nothing natural about monocultures.  Each plant
places different demands on the soil, both giving and
taking.  In their natural environment they would be
integrated with many other species of plants as well as sub
species of their own species.  Different species compliment
each other.  Some repell destructive insects, others attract
pollinating insects, some return nitrogen to the soil,
others providing forage for mega fauna.  Perennials provide
shade, windbreaks, and deep root systems that keep
groundwater coming to the surface in the form of springs and
streams.  Worms provide and in the tropics, ants aerate the
soil.  Insects pollinate and help break down decaying
biomass.  Micro organisms do for plants what micro organisms
do for humans, some keep us alive, others make us sick but
neither of us can survive without the other.  Birds scatter
the dung of mega fauna and are crucial in seed dispersal.

This system was disrupted in the agricultural revolution,
but small farms still had diversity, peasants still relied
on forests for medicines, and variety in their diets.  And
back breaking labour of humans replaced a wide variety of
chores that are achieved in nature without any effort at all.

It was the second agricultural revolution that was part of
the industrial revolution where things really fell apart.

....

Animals -- go through all the primary domesticated animals,
their natures and how they live now.

....

In many respects man hasn't done much better -- 

  - high stress/fear   -- machiavellian techniques, conformity
  - low stress/comfort -- embrace consensus, egalitarianism

....
