#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Fragility
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-fragility.org
:Created:   2017-10-17T19:09@Prek Leap (11.642600N-104.919210W)
:ID:        062400a2-0509-4a63-b2fe-ddceef4d666e
:VER:       561514230.549742345
:GEO:       48P-491193-1287029-15
:BXID:      proj:PAN8-7030
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

 - pale blue dot
 - the skin of an apple
 - all the air, all the water
 - that's all there is, a friable oasis that in cosmic
   scales is as ephemeral as a soap bubble.  like the tiny
   world that Horton the elephant discovers inhabiting a
   mote of dust sitting on a cloverleaf.




 - fragility of our biosphere
   - asteroid and comet strikes
   - solar storms
   - super volcanos
   - hothouse coldhouse

 - fragility of our species

 - fragility of our civilization

 - the idea of progress is a recent infection carried by the
   scientific revolution -- it drives us, but it does not
   direct us in the right direction.  the grasping always
   for more has inspired us as a species, but it has also
   blinded us, made us reckless and squander resources as if
   they were infinite, as if our planet didn't have a
   carrying capacity.  But time and time again, human
   civilizations have run up against the carrying capacity
   of their environment and it always ends the same,
   collapse.  But there was always another civilization
   which could pick up the pieces and rebuild.  We've now
   taken this to it's logical conclusion, there is no where
   left on the planet to go, no greener pastures,
   unexploited resources.  We've finally gone so far that we
   are back where we started.

 - centralized



