#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Yellow Brick Road
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-yellow.org
:Created:   2017-10-17T18:59@Prek Leap (11.642600N-104.919210W)
:ID:        0141018c-a60c-431c-bf74-ad6bff2951e7
:VER:       561513619.820233925
:GEO:       48P-491193-1287029-15
:BXID:      proj:YFB3-8352
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* Brief Histories of the Universe, Earth and Man


 - Bronowski, J., The ascent of man (2011), : BBC Digital.
   cite:bronowski:2011ascent
 - Bryson, B., A short history of nearly everything
   (2003), : Broadway Books.
   cite:bryson:2003short
 - Christian, D., /The history of our world in 18 minutes |
   david christian/ (2011).
   cite:ted:2011:history-david-christian
 - Crofton, I., & Black, J., The little book of big history
   (2017), : Pegasus Books.
   cite:crofton:2017little
 - Harari, Y., Sapiens: a brief history of humankind
   (2011), : Harper.
   cite:harari:2011sapiens
 - Hawking, S., A brief history of time (1998), : Bantam Press.
   cite:hawking:1988brief,hawking:1998brief
 - Langmuir, C. H., & Broecker, W., How to build a habitable
   planet: the story of earth from the big bang to humankind
   (2012), : Princeton University Press.
   cite:broecker:2012how
 - Sagan, C., Cosmos (1985), : Ballantine Books.
   cite:sagan:1985cosmos 
 - Wikipedia, , /Cosmic calendar --- wikipedia, the free
   encyclopedia/ (2017). 
   cite:wiki:2017cosmic-calendar
 - Wilber, K., A brief history of everything (2001), : Shambhala. 
   [Revised Edition]
    cite:wilbur:2001brief,wilbur:1996brief
 - Urban, T., /Putting time in perspective – updated/ (2013).
   cite:urban:2013putting-time

** Representing Time

Big History is pretty fucking cool.  The idea is to tell the
story of the universe (us included) from the perspective of
complexity thresholds since the Big Bang.

Before Big History is the masterful /Cosmos/ by Carl Sagan
which was both a book and television series.
 
Big History uses a timeline, whereas Sagan uses a /Cosmic
Calendar/citenum:wiki:2017cosmic-calendar which he first
used in his book /Dragon's of Eden/citenum:sagan:1986dragons
which presents the 13.7byr history of the universe as a
single calendar month.  This is a far better way for people
to understand the scale of the universe and our place in it.
The timeline needs to compress the space where there is
little information and expand the space where there is more
information which, like 2D map projections of a globe deform
time scales to be able to fit in a space that can be seen at
a glance.  This is not a bad thing, everything is a
tradeoff.  But Sagan's Calendar is better at helping us
understand how small and short a time we have been on the
cosmic stage.

Big History is brilliant, with fantastic graphics.  But the
text is a little dry, it doesn't have the poetry or passion
that Sagan brought to everything.  That's not entirely true,
David Christian's performance at TEDx was fantastic.

The just released /Little Book of Big History/ seems very
good, but it just doesn't have Sagan's genius.

Wait, But Why? has one of the best means of visualizing time
that I've ever seen:

  - [[https://waitbutwhy.com/2013/08/putting-time-in-perspective.html][Putting Time In Perspective]] | Wait But Why

He uses a series of growing timelines.  This works quite
well but doesn't have the same massive in your face impact
that Big History's massive timeline has (mostly because they
had a bigger graphics budget) or the simple but powerful
analogy that Sagan uses to be able to fit such mind blowing
numbers into something that our poor ape brains can grasp.

---

The manifesto was getting too long and un-manifesto like so
most of what I have now as the manifesto will move to the
prologomenon. 

The prologomenon will now serve several purposes: 

  - a collective model of the world for a community/movement
  - an apology and or thesis that the manifesto is based on
  - the foundation for our new liberal arts program
  - a framework that we can use as an outline of knowledge
    that replaces efforts like the traditional hierarchical
    /Propædia/ by Mortimer Adler.  

The Propædia never really caught on in the way that Alder
envisoned.  He saw it as a framework for all knowledge,
education and a model of the sum total of what we
collectively know as a species.  For a while, it was the
first of three parts of the Encyclopedia Briticannica.

The [[https://en.wikipedia.org/wiki/Prop%C3%A6dia][Propædia]] and [[https://en.wikipedia.org/wiki/Microp%C3%A6dia][Micropædia]] were intended to replace the
Index, and the [[https://en.wikipedia.org/wiki/Macrop%C3%A6dia][Macropædia]] was the main body of the
encyclopedia that was in turn made up of articles that
provided introductions and overviews to larger topics, which
would then point, in the references to all the papers and
works that make up the body of knowledge.

This concept was a big influence on many of my original
ideas in BMF.  Scope, Micro and Macro notes were intended to
work in the same way as Adler's vision for Britannica.

It turned out to be a clunky interface in physical print.
The [[https://en.wikipedia.org/wiki/Microp%C3%A6dia][Micropædia]] was a poor replacement for the index.  But it
might have been an excellent electronic interface, where the
Micropædia entries could be returned as search results, and
the Propædia be used as a framework for a thesaurus of terms
for everthing in the Micropædia which would become in effect
a graph database.

At first glance it would seem that Wikipedia has rendered
this vision obsolete, but I don't see it that way.  

Rather, wikipedia could be seen as a first, living draft of
a Macropædia that is always in the process of becoming
something else.  But it provides no /intellectus/, no way of
seeing how everything fits together.  It's just one dam
article after another.  And Wikipedia is poor at being a
gateway to all literature on a subject.  That's not a
criticism, it's just the way that it was designed.  But that
is very much needed.

* Quotes

#+begin_quote
The Earth is the cradle of the mind, but we cannot live
forever in a cradle. 

-- Konstantin Tsiolkovsky (1857-1935)
#+end_quote


#+begin_quote
You can't cross the sea merely by standing and staring at 
the water.

-- Rabindranath Tagore (1861-1941)
#+end_quote


#+begin_quote
You begin saving the world by saving one man at a time; all
else is grandiose romanticism or politics.

-- Charles Bukowski (1920-1994)
#+end_quote

#+begin_quote
Pass it on .... That's the game I want you to learn to play.
Pass it on.

-- Alan Bennett, /The History Boys/
#+end_quote



* I.   The Yellow Brick Road

Is there anybody out there?  The question hangs in the air,
everyone holding their breath, straining to hear in the
uncomfortable silence.  We are terrified of being alone,
alone in the dark, in the crowd, to be the first to speak
out, and to wake in the middle of the night with no one
beside us.  But we are just as scared of who might be out
there in the darkness beyond the warm flickering safety of
the fire; a lion, a monster, a ghost of those and those
things we don't care to remember or re-live.  Part of the
problem is that as a species we evolved to be in the middle
of the african savannah ecosystem.  We weren't at the
bottom, but we certainly weren't at the top.  Lions and
tigers and bears, indeed...

Our ascension to the top of the food chain was recent and so
rapid that the slow mills of evolution didn't have time to
grind out the psychological perks that come with being an
apex predator.  We don't have the casual confidence or raw
muscle of the lion, the deft, deadly resolve of the tiger or
the plodding heavy certainty of the bear.  In the end we are
still fearful apes who have just come down from the branches
long enough to make a mad dash for the next clump of trees
where there are some tasty looking figs.  So even today we
still whisper, often secretly to ourselves, "is there
anybody out there," uncertain if we really want to know.
But there is no answer, not yet.

We live in a cosmos made up of hundreds of billions of
galaxies flying apart from the explosion that gave birth to
our universe.  Each galaxy is made up of hundreds of
billions of fireballs burning holes in the fabric of
spacetime as they orbit, hurtling around each other.  From
time to time one may collapse into a darkness so absolute
that not even information can escape.  Other times some may
explode and for a brief moment outshine all of the other
fireballs in the galaxy, to become vast gas clouds of
astonishing beauty that in turn become the stellar nurseries
where new stars are born.

As gravity clumped, collided and collapsed the gas and dust
into itself, a star was born some 13.7 billion years ago in
such a nursery, in an uninteresting part of a spiral galaxy
we now call the Milky Way.  Orbiting this star are nine
planets, and billions of planetoids made up of rock, iron
and ice, including a small rocky world orbiting close enough
to the star for there to be water in a liquid state.

The more we learn about the universe and our place in it,
the more it's clear that there is nothing special or unique
about us.  We are now discovering, almost every day, the
rocky worlds and gas giants that are orbiting the stars in
our stellar neighborhood. In the coming decades we will have
the ability to learn the composition of the atmospheres of
these worlds.  There is no reason to think that we won't
find other worlds, close enough to their stars to be water
worlds like ours.

But if there is nothing special about us, then it's
reasonable to expect that life will have evolved on other
planets and might even be relatively common.  And, that on
some planets where there is life, that a species evolves 
to build a technological civilization like ours.  

So where is everybody?  This question is known as the Fermi
Paradox.  There is a long list of reasons we haven't yet
found evidence of other technological civilizations, but
there is one reason that haunts the dreams of many
scientists.  What if the reason that we haven't found anyone
out there is that technological civilizations are are by
their very nature so unstable that they destroy themselves
shortly after the start of their own scientific revolution.

Is this our fate as well?  Are technological species little
more than mayflies that have a brief frantic existence
before falling dead in the dark hours before dawn?  It's
called the Great Filter, the existential moment of truth
that a technological race must face after they have unlocked
nuclear forces that power the stellar infernos.  Or, perhaps
what destroys them is learning how to reshape the structure
of life itself as if it were nothing more than a child's set
of lego bricks.  Or, that in their ignorance and immaturity,
they leverage their new found technological prowess to do
nothing but overrun their planet with their numbers, exhaust
all easily exploited mineral and energy wealth and exceed
their planet's carrying capacity and then collapse and not
have the resources to re-build an industrial civilization.

If this sounds familiar it should be.  If we fall now, there
is no rebuilding. The surviors will eek out an existence as
best they can until an asteroid or super volcano, or ice age
finally puts an end to the great human experiment.

Our ancestors understood that there were forces in the
universe which even the gods could not escape, to which they
they gave names like Fate. Fate could not be petitioned, or
sacrificed to, or even hear us if we did.  The Gods might
intervene in some small ways on our behalf, if they could be
bothered.  But ultimately these things were beyond even the
vast powers of the immortals.

It was thought that these forces determined what and how
things happened, but it turned out that fate was nothing
more or less than the physical laws of the universe which
are governed by the complexity of everything interacting
with each other.

You can predict the outcome of simple systems.  But once a
system crosses a threshold of complexity, all there is, is
statistics.  It's a bit like the game of Go.  In Go, binary,
black and white stones are placed on a grid cut into a block
of wood.  We thought that Fate and the Gods added, removed
and moved stones on the board in a dance that we could not
understand, control or predict.  Instead, stones are dropped
onto the board at random, white and black with an equal
chance of any stone landing on any square. What you get is a
Poisson Distribution where you can predict how many squares
on the grid will have how many stones, but not which squares
will have which number of stones.

There is no prayer that can change the certainty of our
uncertainty.  As individuals we must each learn to make
peace with the unknown.  Our consolation is that over time
scales that are beyond the living memory of any individual,
we contribute to collectively beat fate, pass the test and
make it through the Great Filter, but only if enough of us
as individuals today, and tomorrow, decide to do so.

This is the great task we must choose or perish trying.
This is where we must begin, with a single step, at the
center of a widening path spiraling out into a vast kingdom
that we still know little about.  Each tenuous step forward
will often require us to retrace our steps back.  But there
is nothing for it but to push on down the yellow brick road
to learn something that, or meet someone, who can help.
