#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Filters
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-filters.org
:Created:   2017-10-17T19:03@Prek Leap (11.642600N-104.919210W)
:ID:        fb21fc98-959b-4830-ac18-ea28d0a83db1
:VER:       561513899.774837850
:GEO:       48P-491193-1287029-15
:BXID:      proj:WTY3-1200
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


start with life arising after the earth cools -- it could
have arisen here, or elsewhere and piggybacked on a comet or
meteriod -- it's possible it might even be from another
star, riding on a piece of rock ejected from another planet
on another star at some distant time in the past when our
star brushed up against our neightbor's Oort cloud and
exchanged debris -- caught in our Oort Cloud for millennia
before some random event pulled it in towards the sun but
impacted earth first.  we will only know if we ever visit
the stars and find life there that is us... In any event,
somehow, some xxx years ago life began.

filters for life on earth have come in the form of five
great events that resulted in catastrophic climate change
where 75-96% of species on the planet were wiped out

 - End Ordovician, 444 mya, 86% of species lost 
 - Late Devonian, 375 mya, 75% of species lost
 - End Permian, 251 mya, 96% of species lost
 - End Triassic, 200 mya, 80% of species lost
 - End Cretaceous, 66 mya, 76% of all species lost

life is tenacious and antifragile, once it takes hold, it's
astonishing how much punishment it can take and eventually
rebound, stronger and more complex than ever.

the extinction events have acted like the black plague that
wiped out xxx% of the world's population, or the great fire
of london -- it cleaned things out and reset the clock
setting the stage for an evolutionary explosion of new life
racing to fill in all of the ecological niches that had been
left vacant. without the past four extinction events life on
earth may well only be marginally different from how it was
in the Ordovician.  Life has a tendency to reach
equilibriums that can last a very very long time.

the patterns are very clear, and they scale -- climate
change, carrying capacity of an ecosystem, carrying capacity
of a biosphere -- impact the climate and you change the
carrying capacity -- when this happens to an ecosystem in a
biome species go extinct.  when this happens to the
biosphere, you get mass extinction events.

mankind has moved from the small stage of impacting and
being impacted by specific biomes, to being a major player
effecting the entire biosphere.  and we're now doing this in
timescales that can be measured in 2-3 generations.  if that
doesn't blow your mind you weren't paying attention.  if it
did blow your mind and you aren't terrified then there is
something wrong with you.  and if we as a species aren't
terrified by this enough to change our behavior then we are
lost.


