#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Cognition
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Cognition
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-cognition.org
:Created:   2017-10-17T20:02@Prek Leap (11.642600N-104.919210W)
:ID:        0dae7812-a5c3-4d56-ba58-032f1e541fd8
:VER:       561517400.612487036
:GEO:       48P-491193-1287029-15
:BXID:      proj:WKG8-7585
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:



- extend & externalize
   - mind  : brain, speech, writing (havelock), computer
   - muscle: hand, tool, machine, robot
 - transactive man
 - cooperation & war
 - polis -- the rise of annuals and decline of perennials
 - pace layers

 - cognitive revolution
   - we had to give up our intestines which provided more
     energy for the brain but limited our diet -- so without
     cooking we survive poorly
   - we gave up our hearing to dogs
   - childbirth became quite dangerous
   - children born prematurely -- need long period of care
     but means that children's development can be molded
   - we have more nerve endings in our hands

  - we are the planet's apex predator and keystone species,
    capable of destroying everything, we are close to being
    able to consciously control of our dna not only of our
    selves but all life on the planet, we are also close to
    conquering death, so the only thing left that is certain
    is taxes.

    the problem is that we moved up the food chain because
    of cognitive development, it happened too fast for the
    surrounding ecosystems to adapt to us as the new apex
    predator which would have put checks and balances on
    human growth.  second, man may have become smarter, but
    she is still saddled with all of the baggage of an
    animal in the middle of the food chain -- we don't have
    the self-confidence of an apex predator.  It's like
    giving a cow an uzi, vegitarian megafauna like cows know
    that they are on the menu of a wide variety of
    predators, so they are nervous and easily spooked.  Give
    them a WMD and they would hit the button at the first
    unexpected sound of a snapped twig in the grass.
    human's are that much better.

  - stories make cooperation between large groups possible
    - havelock and homer as oral cultural encyclopedia

  - between 70-30kya sapiens developed speech -- if near
    human extinction happened 75kya that corresponds to
    development of human speech only a few thousand years
    before?



  - stories -- gossip makes larger groups possible



