#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Social
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Social
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-social.org
:Created:   2017-10-17T19:11@Prek Leap (11.642600N-104.919210W)
:ID:        7ab1a10f-ed40-4354-8b9b-52c21b9895be
:VER:       561514334.473589960
:GEO:       48P-491193-1287029-15
:BXID:      proj:DKT5-5160
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:


Cognitive estrangement -- we are brains that learn about the
world second hand through very limited senses that evolved
for specific functions -- we try to piece together what the
world is but it's always a hacked together hodgepodge of
sensory information, memories and conjecture about things
that we don't have direct knowledge of.

We expand what we as individuals can learn about the world,
with intersubjective information from other people through a
cultural encyclopedia of myth, cooperative rules and
language that allows us to both communicate and experience
the world in a similar way with others.  Shared belief
systems take the form of religions, ideologies, folklore,
customs, and ritual.  Religions help us fill in the gaps of
our knowledge of things that we don't know or can not know
with shared stories of divinities who by and large are
little more than cardboard projections of our selves and our
fears and anxieties on the cave wall we believe is the
universe.  This is something that hard core atheists can't
understand.  They see religious belief systems as
objectively false.  But they believe in all sorts of
collective belief systems which are fictions as well. But
it's not about objective or empirical truth, which doesn't
matter much.  A fundementalist Christian who proclaims that
the scriptures are objectively and historically accurate
accounts don't live their lives as if it were true.  If they
really believed such things to be real, they could not
function in a modern technological society.  They use
technology daily that could not have been developed if it
were.  This does not excuse willful ignorance of things like
climate change.  But at the same time it doesn't make them
hipocrites.  Belief is not about being true or false, it's
about shared narratives that make cooperation and
communication possible.

Secular belief systems include things like nationality,
cultural identity, money, the market, and above all the
future.  These belief systems make up the mortar that holds
together the bricks that make up civilization.  They are all
stories, narratives that thread through our individual and
collective world maps that we carry around in our heads that
comprise all we know about the world at any given moment.

We need to learn to see these fictions as stories that we
have made up, while embracing them, not as literal truth but
for the power they wield in getting billions of clever apes
to work together and do astonishing things.  We will always
be storytellers.  It is stories that define us, as no other
species does.  But stories are always a mixture of the
subjective and empirical objective experience.  They form
what I call /fnords/.  A fnord is an assertion which is a
probability cloud of all possiblilities about the statement
both as true or false which don't resolve until they have
been placed in context by observation.

Before the great monotheistic religions, Buddhism,
Christianity and Islam came along, reglions were very local,
they literally sprang from the ground around us in
primordial animistic belief systems grounded in specific
rocks, trees, mountains and rivers.  They weren't terribly
portable if you tried to get people from a different place
with different rocks and trees who had their own ideas of
what they were called.  Monotheism was universal, a stripped
down belief system that could map over any local belief
system and over time mostly replace them.  In other words,
monothesim is a belief system best suited to empires. 

The Romans never tried to replace the local gods of the
lands they conquered, but then they didn't have to.
Polytheism is not a zero sum game.  So long as the conquered
paid lip service to the Roman gods they were free to worship
their local gods however they pleased.  Monotheistic belief
systems could never do that -- you either believed and
became one of /us/, or you were /other/ which needed to be
destroyed.

This inflexibility, surprisingly, was a boon for far flung
empires who demanded that you were all in or nothing.
Harsh, but effective.  But this never entirely worked.
Different groups of people interpreted the single scriptures
differently and began fighting with each other.  It's not
easy to get everyone to believe the same thing, we live in
very different climates, and cultures built to adapt to
those climates.  We experience and see the world differently
depending on our relationship to the natural world.  If you
live in a warm pleasant climate, you tend to see the world
as being benign and even friendly.  If you live in an
extreme climate, the world is a hostile place full of
uncertainty and danger.  We bring those attitudes with us to
every part of our lives.  It's no surprise that the Big
three have never been able to get everyone on the same page
for long.  Sadly, we tend to hate those the most, who are
closest to us.  The wars between catholic and protestants
are some of the most bloody an devastating in history.


 - the mind's illusion
 - myth of progress

 - estranged from ourselves
   - savannah lost

