#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Life
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-life.org
:Created:   2017-10-20T08:15@Prek Leap (11.642600N-104.919210W)
:ID:        563bceff-86c9-4e71-84c1-a68e4a949626
:VER:       561734171.446045487
:GEO:       48P-491193-1287029-15
:BXID:      proj:LQR3-4347
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

All too often evolution is framed in terms of competition, of winners
and losers.  But perhaps evolution is better thought of as a story of
cooperation, multicellular life, complex organisms, complementing,
feeding and reinforcing each other to create a biosphere made up of
many interdependent ecosystems.  Man is a success story only because
of cooperation, of small bands of hunter gatherers, of villages and
cities, and the civilizations that weave them together.

The conceit of the individual is a culmulative illusion, a fiction
fabricated by our brain attempting to piece together a continious
model of the world around us while working around our physical and
cognitive limits.

We are the true children of Janus; holons made from countless parts,
that make a whole, even as that whole is in turn just a part of
something much larger than ourselves.  It's all turtles, all the way
down, and all the way up.  We're just a turtle in the middle.
