#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Savannah
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* Savannah
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-savannah.org
:Created:   2017-10-17T19:07@Prek Leap (11.642600N-104.919210W)
:ID:        affde5b7-6751-4d6d-8393-6acc00b97a17
:VER:       561514140.276306520
:GEO:       48P-491193-1287029-15
:BXID:      proj:IRW3-7212
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:


The road for us really started in the African savannah, the
biome where we evolved and became what we are along side a
number of other cousins of great apes including our closest
cousin the Chimpanzee.


A savannah is a biome between worlds, stalled in the process
of evolving from a grassland to a forest.  Savannah biomes
are enormously productive and varied, with the advantages of
both grasslands and forests while making both stable and in
harmony with each other.  Where grasslands are the domain of
annuals which die out every year, and forests are dominated
by perrenials which often live decades or even centuries
under the right conditions, a savannah is a balance between
the two, and so support a wider variety of both flora and
fauna in an ecosystem which is resiliant to a wider variety
of climatic and other types of change than.

Fauna make a savannah what it is, with a combination of mega
fauna which both graze grasses and keep the ground clear
beneath trees and by knocking down or tearing up most small
trees that would otherwise eventually grow to replace the
grasses.

Some 6 million years ago, we shared an ancestor who had two
chilren, one which would evolve to become the Chimpanzee and
the other would become the genera /Homo/ which means Man.

/Homo Neanderthalensis/ (man from the Neander Valley) who
was larger and stronger than us, dominated north western
Eurasia and was adapted to the cold of the Ice Age.  /Homo
Erectus/ (upright man), was adapted to the warmer African
climate who lived for almost 2 million years.

On the island of Java in what is today called Indonesia
there was /Homo Soloensis/, (Man from the Solo Valley) who
was well adapted to life in the tropics, and the species
recently discovered in Flores called /Homo Floresiensis/
which reached a maximum of a bit more than a one meter in
height.  In 2010 the finger bone of a previously unknown
species, /Homo Denisova/ was discovered in the Denisova Cave
in Siberia.  We may never know how many other lost species
of ours there are to be found.

Meanwhile, in the African savannah, the cradle of humanity,
new species evolve including /Homo Rudolfensis/ (man from
Lake Rudolf), /Homo Ergaster/ (working Man), and our
species, who was modestly named by Linnaeus in 1758, /Homo
Sapiens/ (wise Man)

A hundred thousand years ago there were at least six
different human species living at the the same time, spread
across the planet.

It's still uncertain why any one species vanished, though
there are many theories that all posit that we were
responsible for the demise of some species when sapiens
moved into the territories of other species.

The Toba super erupution that took place around 75,000 years
in what is now Indonesia coincided with the extinction of
most species of Homo and almost took us with it.  From
genetic evidence, the human population was reduced to only a
few thousand individuals who had all come out of africa.
For a long time it was thought that the eruption was
responsible for our near extinction, but there is a growing
body of evidence that man was able to cope with the
erruption quite well and that little volcanic ash reached
east Africa which quickly recovered.

----

Mankind is a broader concept than a catalog of species of
the Homo genera.  The Savannah is an ecosystem of
interdependent species of which, for most of sapien's
history was in the middle of the food chain.

Man domesticated a number of animals who would not survive
without us, they are part of us, and we depend on them for
the survival of our species as much as they on us.


We must learn to reclaim the savannah as part of ourselves,
it is not only where we are from, but what we are.  And when
we leave the planet to spread our species and civilization
across the solar system, and eventually to the stars, we
will bring the savannah with us.
