#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Polis | Manifesto
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/manifesto-polis.org
:Created:   2017-10-28T10:38@Prek Leap (11.642600N-104.919210W)
:ID:        e23ed9f1-530b-4e8f-9cfa-e0045e3ed0d9
:VER:       562433977.494582515
:GEO:       48P-491193-1287029-15
:BXID:      proj:LOF3-8407
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

I've never felt comfortable with the idea of ubanization -- there was
always something that smelt wrong about it.  A city is simply a human
monoculture.  Nothing good comes from monocultures of any type, so why
should human monocultures be a good thing?

There is a growing body of evidence that cities and states did not
arise as naturally as we've been told -- and that there was a great
deal of resistence to urban life.  It would seem that people were
forced to live in cities and states as captives, or slaves.  Life in
cities was and still isn't very nice.

There are a number of people I respect who wax poetic about cities and
urban life, including Steward Brand, but I've never bought into it.

The advantages of cities all comes down to communication and logistics
-- when people live close to each other they can coordinate and
cooperate in ways that a population spread over a large area can not
do.

This is no longer true -- the Internet will soon make these advantages
largely moot.  Not quite yet, but soon.  Once telepresence becomes the
norm it will be.  But it's still a lot more complicated than that.
The challenge is to build a distributed civilization that is
geographically spread out somewhat thinly, but still remain
cosmopolitan -- that means that though we are spread out, we can not
be completely sedantary -- we must be mobile so that we can live and
work and learn to commiunicate and cooperate with a wide variety of
different people.  Cities have traditionally done this.

----

The other problem is the whole concept of the state -- which provides
a number of functions that seem to be equally benificial and
repressive at the same time.

States create hierarchies that create power and wealth imbalances.
The larger those imbalances are, the worse off most people are.
States serve those at the top of hierarchies, and give those people
freedom, security, liberty and comfort -- but those at the bottom are
trapped, poor, often sick, and miserable.

At the base of all of this are cereal crops which are, as Scott points
out, both legible and taxable.  If you control the land, and control
the people on the land, cereals are the best way do to do both.

Egalitarian societies don't scale -- 

States and land ownership seem to the two of things holding us back
more than anything else.
