#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall

* Chenla Manifesto | README
:PROPERTIES:
:CUSTOM_ID:
:Name:     /home/deerpig/proj/chenla/manifesto/README.org
:Created:  2017-10-04T20:34@Prek Leap (11.642600N-104.919210W)
:ID:       200062fd-c7b8-4adf-bdc0-62c8c9ee9306
:VER:      560396113.933103197
:GEO:      48P-491193-1287029-15
:BXID:     proj:VSX8-8051
:Class:    primer
:Type:     readme
:Status:   wip
:Licence:  MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]]
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-readme-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

*PLEASE NOTE: 2018-04-19, Prek Leap*

This archive is in the process of being deprecated. We are
slowly moving all contents that are worth keeping to their
new home which is part of Warp & Woof, APPL, Hoard and
Primer.

As we process each file, it will be moved into the ./archive
directory.  When we've finished moving everything there, the
entire repo will be deprecated and archived.

---

Bibles are the traditional place for /canonical/ origin
stories.  I emphasize canonical because in a Bible, those
stories are to be taken on faith and are not allowed to be
questioned.  That's why I prefer manifestos which often
include origin stories as well in the form of historical
supporting material meant to buttress and justify the claims
made in the manifesto.

In modern times a manifesto is thought of as a call to
change the present order, a call for revolutionary regime
change and a declaration of the ideological foundations that
the new order shall embrace.  So Marx's Communist Manifesto,
Anselme Bellegarrigue's Anarchist Manifesto, the United
States Declaration of Independence all fall into this mold.

A good manifesto not only defines what we are, but what we
aspire to become in broad strokes apon the very walls and
battlements of that which it intends to replace.

This embodies the concept of /scope/, the surrounding
context of what something is that must be included if it is
to be understood.  Scope is Mnemosyne's forgotten half
sister, unique among the imortals who is afflicted with a
memory limited to that of the span of two or three mortal
lifetimes at most.  Try as she might, her memories are in a
constant state of fading so that she is doomed to relive and
make the same mistakes time and again.

