#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Overview | Roadmap
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/roadmap-overview.org
:Created:   2017-10-24T20:56@Prek Leap (11.642600N-104.919210W)
:ID:        377bb928-3372-49d4-b6df-079892639a00
:VER:       562125446.126624601
:GEO:       48P-491193-1287029-15
:BXID:      proj:GOE7-7863
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction


The roadmap combines a couple of different things:

  - timeline for population projections
  - timeline for mars and industrialization of space
  - timeline for rolling out d9d -- where d9d is a network of nodes
    which represent people, devices and processes (micro value-chains)

What we need to be looking for is two tipping points; when
colonizing mars and the industrialization of space becomes
inevitable and second, when mankind becoming a distributed
civilization becomes inevitable.

Making mankind a multiplanet species is not enough,
civilization has to become truly distributed, not just
decentralized.  If mars becomes a viable place to live, it
will still not make civilization safe unless is it also
completely independent of earth -- so that if earth vanishes
one day, civilization on mars will continue on uneffected.

So we need to estimate how many specializations are required
for civilization to be distributed at several levels of
existence.

  - industrial edwardian
  - info-tech -- which is likely a bit more advanced than
    today, but based on advanced computing, networking,
    materials science, genetic manipulation and medical.
  - full blown AI/Robotics

I don't think mars will be possible at the first two stages
until century or more of development has created stable long
term habitats and set terraforming processes in motion.

Industrialization of space will not be possible at the first
two levels as well.

The number of specializations depends on how many of those
specializations can be handled per person.  In an ai/robotic
civilization, a single person will be able to manage
multiple specializations through force multiplication,
autonomous systems and allowing ai systems to become
extented and externalized cognitive processes

The roadmap could break down specializations into different
layers that represent different aspects of civilization

transporaton, communication, energy, healthcare, education,
construction, agriculture

but this doesn't solve things either because we need to also
know how many instances of a specialization is needed for a
given population -- this gives us a measure of how
distributed something is.  and if that isn't complicated
enough, distribution is not going to be nice and neat with
all required specialities needed for a particular area to be
within that area -- a given area (say a bioregion) doesn't
need to be a complete independent instance of civilization,
but it does need to have access to everything, and if they
don't produce it, they need access to enough redundent
sources of it.  so if we have a bioregion with 2 million
people, it might be able to produce locally, say 60% of
everything they consume, but that other 40% might spread
over many other bioregions.

we will also need to have in place the ability to jumpstart
specilties when the number of instances of that specialty
falls below a critical number.  The knowlege of being able
to do that should be the most distributed thing of all --
ideally, every bioregion should have all of the knowledge
and means to create /every/ specialty locally if they need
to.  not a trivial problem.....
