#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Theses Notes
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* These Notes
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/manifesto/theses-notes.org
:Created:   2017-10-18T19:47@Prek Leap (11.642600N-104.919210W)
:ID:        55b408df-ddcd-4060-aa6c-5c541f1bfebd
:VER:       561602887.446933926
:GEO:       48P-491193-1287029-15
:BXID:      proj:UPE1-8100
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:


** Notes

  - we must bring the savannah with us where ever we go --
    we need to learn to create and manage the biospheres we
    live in, and move to an ecological accounting system
    that really balances

  - the illusion of wilderness -- man has had a far greater
    impact on the planet than we want to admit -- we were in
    large part, responsible for the extinction of a huge
    swath of megafuana around the planet from mastadons, to
    giant slothes -- in north america, austrailia, new
    zeland -- american's like to wax romantic about the
    great untouched wilderness of north america with the
    original people's living there living in harmony with
    nature.  The jaw dropping landscapes of John Muir, the
    thunderous herds of bison numbering in the millions
    didn't exist two hundred years before Muir took up his
    paint brush -- the wilderness had only been untouched by
    man after small pox and the plague wiped out 80-90% of
    the population in the America's when early contact
    between Europe was made with the America's.  The
    pilgrams literally built their colony on the bones of
    the dead.

  - we will need to master of geoengineering -- first, to
    carve out habitable places in the cracks and crevices of
    the solar system, and eventually, to fix the mess we've
    created here on earth.

  - we need to become a truly distributed species

  - the city is not the savannah, and it never can be --
    cities exist because of the limitations of moving goods,
    people and knowledge -- if you can truly distribute
    those three things, then the mega cities we have today
    will no longer be needed.

  - we need to learn to manage the savannah inside us as
    well, our aggressive tendencies, our cognitive biases,
    our innate laziness, greed and tribal territorialism --
    we can no longer afford these luxuries and must set them
    aside as childish things

  - we must stop thinking of ourselves as a single species
    and embrace our transactive nature a broader concept of
    mankind that includes everything from our dogs and
    eventually to ai

  - we must let go of the illusion of the individual --
    homesteaders, doomsday preppers,

    even Thoreau, living his solitary life, relied on tools
    that had been created by an industrial chain that mined
    and refined ore into metals that were turned into tools,
    on textiles that started with farmers growing cotton or
    shearing sheep, which were spun into threads which were
    died different colors and woven into fabrics that were
    fashioned into clothes.  His shoes and boots started
    with the hides cut from megafauna, which was tanned and
    and fashioned into his shoes and boots.  and finally, he
    relied, though it's not certain how much, on food that
    was cooked by his mother (the story of his mother came
    from the permaculture book).

  - we are wired to wander but not be cut adrift as
    individuals but as members of small bands of 10-25
    people.  this is very natural -- children grow up and
    marry into other bands.  bands should be responsible for
    raising children culturally, and economically.  when a
    child is born into a band it is tied as much and perhaps
    even more to the band more than to the parent -- it
    doesn't take a village to raise a child, that's too
    large a cultural construct -- it has always been the
    band.

  - my concept of shops as economic production units that
    are responsible for several extending families is a
    perfect match for this new concept of a band -- perhaps
    the band itself is a legal entity that is also an
    economic entity as well.  the more I think about it,
    this is likely the only way a band could become stable.

  - as our lifespans increase, we will likely change from
    being a species with a single arc of youth, middle age
    and old age, to a very long middle age where we will
    cycle through a cycles of career, and child rearing.
    Each of these cycles might be within the same band, but
    more likely we will form a band to either have a career
    or raise a child, and when that cycle is over when the
    children have grown and gone off you will take a break,
    grow bored and then move on to form another band.  This
    would constitute a kind of rebirth for the individual to
    start fresh and recharged for a new cycle of their
    lives.  perhaps this would even correspond with a
    physical rejuvenation as well -- getting treatment to
    turn back the clock a couple of decades, perhaps
    changing your ethnicity, culture, language, or even
    gender to begin a new cycle.

  - this solves a problem which has bothered me for a long
    time.  rural communities can be both stable, nurturing
    places for people to live, work and raise families.  But
    they also become inbred, and moribund -- economically,
    educationally, and culturally they can get stuck as
    well.

    I've long wondered how the whole town-gown problem could
    be solved, as well as the toxicity and hopelessness of
    small isolated towns.  The answer is not to let children
    have their adventures at college abroad and then come
    back to settle down -- there needs to be a mechanism to
    bring in fresh genes, fresh ideas and experiences.


  - we need to stop thinking of ourselves as being one
    person from birth to death -- we are different people at
    different times in our lives and need to acknowledge
    this fact and reflect it in the way we treat things like
    success and failure and mistakes made.  this is
    especially true when it comes to mistakes -- you make a
    mistake, and should be held accountable for that mistake
    in the arc you are in, but eventually you will evolve
    into a different person and that person should be given
    the chance to start a new arc fresh -- but this will
    take time for us to learn how to do.

  - rituals of divorce -- our cultures are wired for single
    arc lifetimes -- we need to provide stable environments
    for each arc, but when it doesn't work out we must have
    a means of moving on.  Children should be tied to a
    single band until they become adults and ritually leave
    the band to seek their fortunes.  Adults should also be
    able to complete their cycle and move on as well.
    In this way bands will live and breath over time.
    divorce should never be easy -- but it must become part
    of the natural part of our societies, a doorway to a new
    beginning not simply an end.

  - joining a new band will, in many cases happen through
    marriage -- and we can use the ancient japanese
    tradition of men joining a japanese business through
    marriage and actually being adopted and changing their
    names to become part of the family to eventually take
    over the family business.  changing names is very
    important -- a clean slate -- the modern concept of a
    family is quite new, the idea of families going back
    tens or hundreds of generations used to be quite rare.
    family names are a new thing as well -- which was
    imposed by states to make people legible.

  - bands will be corporate entities -- and hold property
    and other assets that are collectively owned by the band
    and stay with the band.  when you leave a band, the band
    finances that person to leave and help found a new band
    or to join another band -- this is not the same as a
    commune, it will be closer to a hamlet.  membership in
    the band will include the concept of equity, but it will
    be equity that is tied up, a prosperous band will be
    able to provide more financing for those leaving the
    band, but beyond that there isn't really much of a
    mechanism or incentive for individuals to become
    independently wealthy or powerful.  how will that play
    out?  will there be bands who are focused on becoming
    wealthy and powerful and become new political and
    economic elites?  what about people in between bands?
    will being bandless will be equivilent to being
    stateless?  how can that work?  there is the concept of
    the jack, a person who has finished training under a
    master and travels from place to place getting
    experience before they produce their /master work/ and
    become a master.  this is, in a sense a stage of life,
    and we will need systems to support this.  perhaps each
    band will traditionally keep slots open for jacks, sort
    of in the same way as my family kept a bedroom for the
    local school teacher to live

  - educationally, you complete the trivium while living in
    your birth-band.  Then you either become an apprentice
    in your own band or in another band?  the same mechanism
    will work for jacks.  then when you become a master you
    join or form a band and become a full member.

  - none of this is as speculative as it might sound at
    first, we have effectively nearly doubled our lifetime
    already and we have a prolonged middle age which is
    longer than it takes for a single arc already 

  - how do we kickstart all of this?  the transition will
    not be easy, so we need to provide motivation for people
    to adopt this new, but very old, way of life.  this
    needs to start with social contract -- join the group
    and you will get protections and benifits for life (or
    at least the time that you are in the band).



